image: gradle:jdk8

stages:
  - build
  - test
  - deploy

build-jvm:
  stage: build
  script:
    - ./gradlew jvmMainClasses
    - ./gradlew jvmTestClasses
  artifacts:
    paths:
      - source/build/

test-jvm:
  stage: test
  script: ./gradlew jvmTest --parallel
  dependencies:
    - build-jvm

pages:
  stage: deploy
  script: ./gradlew dokka
  dependencies:
    - build-jvm
  when: manual
  artifacts:
    paths:
      - public
  only:
    refs:
      - master

deploy:
  stage: deploy
  script: ./gradlew bintrayUpload
  when: manual
  only:
    refs:
      - master
    variables:
      - $BINTRAY_KEY
