image: registry.gitlab.com/serebit/strife:latest

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle
  SNAPSHOT_VERSION: "$CI_COMMIT_REF_NAME-commit-$CI_COMMIT_SHORT_SHA"

before_script:
  - rm -f .gradle/caches/modules-2/modules-2.lock
  - rm -f .gradle/caches/build-cache-1/build-cache-1.lock

cache:
  key: one-key-to-rule-them-all
  paths:
    - .gradle/caches/modules-2/
    - .gradle/wrapper/dists/
    - .gradle/caches/build-cache-1/

.base:
  except:
    changes:
      - README.md
      - CHANGELOG.md
      - CONTRIBUTING.md
      - LICENSE.md
      - FUNDING.yml

build:
  extends: .base
  stage: build
  script: ./gradlew build
  artifacts:
    paths:
      - "**/build/classes"
      - "**/build/libs"

deploy-release:
  extends: .base
  stage: deploy
  when: manual
  script: ./gradlew publishAllPublicationsToPublicRepository
  dependencies:
    - build
  environment:
    name: deploy-release
  only:
    - tags

deploy-snapshot:
  extends: .base
  stage: deploy
  script: ./gradlew publishAllPublicationsToSnapshotRepository
  dependencies:
    - build
  environment:
    name: deploy-snapshot
  only:
    refs:
      - master

pages:
  extends: .base
  stage: deploy
  when: manual
  script: ./gradlew dokka
  dependencies:
    - build
  environment:
    name: deploy-pages
  only:
    - tags
  artifacts:
    paths:
      - public
