image: registry.gitlab.com/serebit/strife:latest

variables:
  PUBLISH_BUILD_SCAN: "true"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  DOCKER_DRIVER: overlay2

.deploy-conditions: &deploy-conditions
  when: manual
  only:
    refs:
      - master
    variables:
      - $BINTRAY_KEY

build:
  stage: build
  script: ./gradlew build
  artifacts:
    untracked: true
    reports:
      junit: "*/build/test-results/*/TEST-*.xml"

deploy:
  stage: deploy
  script: ./gradlew publishAllPublicationsToBintrayRepository
  dependencies:
    - build
  <<: *deploy-conditions

pages:
  stage: deploy
  script: ./gradlew dokka
  dependencies:
    - build
  <<: *deploy-conditions
