image: registry.gitlab.com/serebit/strife:latest

stages:
  - build
  - test
  - deploy

variables:
  GRADLE_OPTS: "-Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=true"

build-jvm:
  stage: build
  script:
    - ./gradlew :source:jvmMainClasses
    - ./gradlew :source:jvmTestClasses
  artifacts:
    paths:
      - build/
      - source/build/
      - .gradle/

test-jvm:
  stage: test
  script: ./gradlew :source:jvmTest
  dependencies:
    - build-jvm

pages:
  stage: deploy
  script: ./gradlew :source:dokka
  dependencies:
    - build-jvm
  when: manual
  artifacts:
    paths:
      - public
  only:
    refs:
      - master

deploy:
  stage: deploy
  script: ./gradlew :source:bintrayUpload
  dependencies:
    - build-jvm
  when: manual
  only:
    refs:
      - master
    variables:
      - $BINTRAY_KEY
