image: registry.gitlab.com/serebit/strife:latest

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  key: one-key-to-rule-them-all
  paths:
    - /root/.gradle/caches/modules-2
    - /root/.gradle/wrapper/dists

.base:
  except:
    changes:
      - README.md
      - CHANGELOG.md
      - CONTRIBUTING.md
      - LICENSE.md
      - FUNDING.yml

build:
  extends: .base
  stage: build
  script: ./gradlew build
  artifacts:
    paths:
      - "**/build/classes"
      - "**/build/libs"

deploy-release:
  extends: .base
  stage: deploy
  when: manual
  script: ./gradlew publishAllPublicationsToPublicRepository
  dependencies:
    - build
  environment:
    name: deploy-release
  only:
    - tags

deploy-snapshot:
  extends: .base
  stage: deploy
  script: ./gradlew publishAllPublicationsToSnapshotRepository
  dependencies:
    - build
  environment:
    name: deploy-snapshot
  variables:
    SNAPSHOT_VERSION: "$CI_COMMIT_REF_NAME-commit-$CI_COMMIT_SHORT_SHA"
  only:
    refs:
      - master

pages:
  extends: .base
  stage: deploy
  when: manual
  script: ./gradlew dokka
  dependencies:
    - build
  environment:
    name: deploy-pages
  artifacts:
    paths:
      - public
