image: registry.gitlab.com/serebit/strife:latest

variables:
  PUBLISH_BUILD_SCAN: "true"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  DOCKER_DRIVER: overlay2
  GIT_DEPTH: 10

.deploy-conditions: &deploy-conditions
  dependencies:
    - build
  only:
    refs:
      - master
    variables:
      - $BINTRAY_KEY

build:
  stage: build
  script: ./gradlew build
  artifacts:
    untracked: true
    reports:
      junit: "*/build/test-results/*/TEST-*.xml"

deploy-release:
  stage: deploy
  script: ./gradlew publishAllPublicationsToPublicRepository
  dependencies:
    - build
  when: manual
  <<: *deploy-conditions

deploy-snapshot:
  stage: deploy
  script: ./gradlew publishAllPublicationsToSnapshotRepository
  variables:
    SNAPSHOT_VERSION: "$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
  dependencies:
    - build
  <<: *deploy-conditions
pages:
  stage: deploy
  script: ./gradlew dokka
  artifacts:
    paths:
      - public
  when: manual
  <<: *deploy-conditions
