image: registry.gitlab.com/serebit/strife

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle_home
  KONAN_DATA_DIR: $CI_PROJECT_DIR/.konan_home

before_script:
  - rm -f $GRADLE_USER_HOME/caches/modules-2/modules-2.lock
  - rm -f $GRADLE_USER_HOME/caches/build-cache-1/build-cache-1.lock
  - mkdir -p $KONAN_DATA_DIR/cache
  - ln -s /var/lib/konan/deps/* $KONAN_DATA_DIR/cache/

cache:
  key: one-key-to-rule-them-all
  paths:
    - $GRADLE_USER_HOME/wrapper/dists/
    - $GRADLE_USER_HOME/caches/modules-2/
    - $GRADLE_USER_HOME/caches/build-cache-1/
    - $KONAN_DATA_DIR/kotlin-native-*
  policy: pull

build:
  stage: build
  script: ./gradlew build
  artifacts:
    paths:
      - "buildSrc/build/classes"
      - "**/build/bin"
      - "**/build/classes"
      - "**/build/libs"
      - "**/build/test-results"
  cache:
    policy: pull-push

deploy-snapshot:
  stage: deploy
  script: ./gradlew publishAllPublicationsToSnapshotRepository
  dependencies: [ build ]
  environment:
    name: deploy-snapshot
  only:
    refs: [ master ]
  variables:
    SNAPSHOT_VERSION: "$CI_COMMIT_REF_NAME-commit-$CI_COMMIT_SHORT_SHA"

deploy-release:
  stage: deploy
  when: manual
  script: ./gradlew publishAllPublicationsToPublicRepository
  dependencies: [ build ]
  environment:
    name: deploy-release
  only:
    refs: [ release ]

pages:
  stage: deploy
  when: manual
  script: ./gradlew dokkaHtml
  dependencies: [ build ]
  environment:
    name: deploy-pages
  only:
    refs: [ release ]
  artifacts:
    paths:
      - "public"
