image: gradle:jdk11

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle_home
  KONAN_DATA_DIR: $CI_PROJECT_DIR/.konan_home

after_script:
  - rm -f "$GRADLE_USER_HOME/caches/**/"{*.lock,gc.properties}
  - find "$GRADLE_USER_HOME/caches/" -type d -empty -delete

cache: &global_cache
  key: one-key-to-rule-them-all
  paths: # these are all either deps or necessary build metadata for quick rebuilds
    - $GRADLE_USER_HOME/caches/modules-*/{files,metadata}-*/
    - $GRADLE_USER_HOME/caches/*.*/{file-changes,fileHashes,generated-gradle-jars,gradle-kotlin-dsl,gradle-kotlin-dsl-accessors}/
    - $GRADLE_USER_HOME/caches/{build-cache,jars}-*/
    - $KONAN_DEPS_CACHE/
    - .gradle/{*.*,buildOutputCleanup}/
    - ./**/build/{classes,bin,libs}/
  policy: pull

build:
  stage: build
  script: gradle allTests
  cache:
    <<: *global_cache
    policy: pull-push

deploy-snapshot:
  stage: deploy
  script: ./gradlew publishAllPublicationsToSnapshotRepository
  dependencies: [ build ]
  environment:
    name: deploy-snapshot
  only:
    refs: [ master ]
  variables:
    SNAPSHOT_VERSION: "$CI_COMMIT_REF_NAME-commit-$CI_COMMIT_SHORT_SHA"

deploy-release:
  stage: deploy
  when: manual
  script: ./gradlew publishAllPublicationsToPublicRepository
  dependencies: [ build ]
  environment:
    name: deploy-release
  only:
    refs: [ release ]

pages:
  stage: deploy
  when: manual
  script: ./gradlew dokkaHtml
  dependencies: [ build ]
  environment:
    name: deploy-pages
  only:
    refs: [ release ]
  artifacts:
    paths:
      - "public"
