image: java:8-jdk

stages:
  - build
  - test
  - deploy

build-jvm:
  stage: build
  script:
    - ./gradlew jvmMainClasses
    - ./gradlew jvmTestClasses

test-jvm:
  stage: test
  script:
    - ./gradlew jvmTest --parallel

pages:
  stage: deploy
  script:
    - ./gradlew dokka
  when: manual
  artifacts:
    paths:
      - public
  only:
    refs:
      - master

deploy:
  stage: deploy
  script:
    - ./gradlew bintrayUpload
  when: manual
  only:
    refs:
      - master
    variables:
      - $BINTRAY_KEY
