image: registry.gitlab.com/serebit/strife:latest

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build:
  stage: build
  script: ./gradlew build
  artifacts:
    paths:
      - "**/build/classes"
      - "**/build/libs"
  except:
    changes:
      - README.md
      - CHANGELOG.md
      - CONTRIBUTING.md
      - LICENSE.md

deploy-release:
  stage: deploy
  when: manual
  script: ./gradlew publishAllPublicationsToPublicRepository
  dependencies:
    - build
  environment:
    name: deploy-release
  only:
    - tags

deploy-snapshot:
  stage: deploy
  script: ./gradlew publishAllPublicationsToSnapshotRepository
  dependencies:
    - build
  environment:
    name: deploy-snapshot
  variables:
    SNAPSHOT_VERSION: "$CI_COMMIT_REF_NAME-commit-$CI_COMMIT_SHORT_SHA"
  only:
    refs:
      - master

pages:
  stage: deploy
  when: manual
  script: ./gradlew dokka
  dependencies:
    - build
  environment:
    name: deploy-pages
  artifacts:
    paths:
      - public
