image: registry.gitlab.com/serebit/strife:latest

build-jvm:
  stage: build
  script:
    - ./gradlew jvmMainClasses
    - ./gradlew jvmTestClasses
  artifacts:
    paths:
      - build/
      - source/build/
      - .gradle/

test-jvm:
  stage: test
  script: ./gradlew jvmTest
  dependencies:
    - build-jvm

deploy:
  stage: deploy
  script: ./gradlew bintrayUpload
  dependencies:
    - build-jvm
  when: manual
  only:
    refs:
      - master
    variables:
      - $BINTRAY_KEY
