package com.serebit.strife.entities

import com.serebit.strife.BotClient
import com.serebit.strife.internal.entitydata.GuildEmojiData
import com.serebit.strife.internal.network.Cdn
import com.serebit.strife.internal.network.ImageFormat
import com.serebit.strife.internal.packets.PartialEmojiPacket
import io.ktor.http.encodeURLQueryComponent

/** A small digital image or icon used to express an idea emotion, etc. */
sealed class Emoji {
    /** How the emoji should be presented in the request body. */
    internal abstract val requestData: String
    /** How the emoji should be presented in the URI. */
    internal abstract val uriData: String
}

/** A user-created Emoji which is housed in a [Guild]. */
class GuildEmoji internal constructor(
    private val data: GuildEmojiData
) : Emoji(), Entity {

    override val requestData = data.id.toString()
    override val uriData = "${data.name}:${data.id}"

    override val id = data.id
    override val context = data.context
    /** The name of the [GuildEmoji]. This is used to type the emoji between semi-colons like ``:this:`` */
    val name get() = data.name
    /** The [User] who created this [GuildEmoji]. */
    val creator get() = data.creator?.lazyEntity
    val whitelistedRoles get() = data.roles.map { it.lazyEntity }
    val isAnimated = data.isAnimated
    val isManaged get() = data.isManaged

    /** Get this [GuildEmoji] as a standard Mention (``<name:ID>``). */
    val asMention: String = "<${if (isAnimated) "a:" else ""}$name:$id>"

    /** The URL which leads to the full-sized image. */
    val url: String = Cdn.CustomEmoji(id, if (isAnimated) ImageFormat.Gif else ImageFormat.Png).toString()

    /** Get this [GuildEmoji] as a standard Mention (``<name:ID>``). */
    override fun toString() = asMention
}

/**
 * A user-created [Emoji] which the current client cannot use
 * (i.e. the bot is not a memeber of the [ForeignGuildEmoji]'s housing [Guild]).
 */
@Suppress("UNUSED")
data class ForeignGuildEmoji internal constructor(
    override val context: BotClient,
    override val id: Long,
    val name: String
) : Emoji(), Entity {
    override val requestData = id.toString()
    override val uriData = "name:$id"

    /** Get this [GuildEmoji] as a standard Mention (``<name:ID>``). */
    val asMention: String = "<:$name:$id>"

    /** Get this [GuildEmoji] as a standard Mention (``<name:ID>``). */
    override fun toString() = asMention
}

/**
 * A Standard Unicode [Emoji] represented in [unicode] characters. If the emoji supports a [SkinTone], [tone] property
 * can be set.
 */
@Suppress("UNUSED")
sealed class UnicodeEmoji(val unicode: String, val tone: SkinTone? = null) : Emoji() {
    /** The emoji's [unicode] combined with its [tone]'s unicode, if any. */
    val combinedUnicode: String = tone?.let { unicode + it.unicode } ?: unicode

    override val requestData = combinedUnicode
    override val uriData = combinedUnicode.encodeURLQueryComponent()

    // People

    object Grinning : UnicodeEmoji("\ud83d\ude00")
    object Grimacing : UnicodeEmoji("\ud83d\ude2c")
    object Grin : UnicodeEmoji("\ud83d\ude01")
    object Joy : UnicodeEmoji("\ud83d\ude02")
    object Smiley : UnicodeEmoji("\ud83d\ude03")
    object Smile : UnicodeEmoji("\ud83d\ude04")
    object SweatSmile : UnicodeEmoji("\ud83d\ude05")
    object Laughing : UnicodeEmoji("\ud83d\ude06")
    object Innocent : UnicodeEmoji("\ud83d\ude07")
    object Wink : UnicodeEmoji("\ud83d\ude09")
    object Blush : UnicodeEmoji("\ud83d\ude0a")
    object SlightSmile : UnicodeEmoji("\ud83d\ude42")
    object UpsideDown : UnicodeEmoji("\ud83d\ude43")
    object Relaxed : UnicodeEmoji("\u263a")
    object Yum : UnicodeEmoji("\ud83d\ude0b")
    object Relieved : UnicodeEmoji("\ud83d\ude0c")
    object HeartEyes : UnicodeEmoji("\ud83d\ude0d")
    object KissingHeart : UnicodeEmoji("\ud83d\ude18")
    object Kissing : UnicodeEmoji("\ud83d\ude17")
    object KissingSmilingEyes : UnicodeEmoji("\ud83d\ude19")
    object KissingClosedEyes : UnicodeEmoji("\ud83d\ude1a")
    object StuckOutTongueWinkingEye : UnicodeEmoji("\ud83d\ude1c")
    object StuckOutTongueClosedEyes : UnicodeEmoji("\ud83d\ude1d")
    object StuckOutTongue : UnicodeEmoji("\ud83d\ude1b")
    object MoneyMouth : UnicodeEmoji("\ud83e\udd11")
    object Nerd : UnicodeEmoji("\ud83e\udd13")
    object Sunglasses : UnicodeEmoji("\ud83d\ude0e")
    object Hugging : UnicodeEmoji("\ud83e\udd17")
    object Smirk : UnicodeEmoji("\ud83d\ude0f")
    object NoMouth : UnicodeEmoji("\ud83d\ude36")
    object NeutralFace : UnicodeEmoji("\ud83d\ude10")
    object Expressionless : UnicodeEmoji("\ud83d\ude11")
    object Unamused : UnicodeEmoji("\ud83d\ude12")
    object RollingEyes : UnicodeEmoji("\ud83d\ude44")
    object Thinking : UnicodeEmoji("\ud83e\udd14")
    object Flushed : UnicodeEmoji("\ud83d\ude33")
    object Disappointed : UnicodeEmoji("\ud83d\ude1e")
    object Worried : UnicodeEmoji("\ud83d\ude1f")
    object Angry : UnicodeEmoji("\ud83d\ude20")
    object Rage : UnicodeEmoji("\ud83d\ude21")
    object Pensive : UnicodeEmoji("\ud83d\ude14")
    object Confused : UnicodeEmoji("\ud83d\ude15")
    object SlightFrown : UnicodeEmoji("\ud83d\ude41")
    object Frowning2 : UnicodeEmoji("\u2639")
    object Persevere : UnicodeEmoji("\ud83d\ude23")
    object Confounded : UnicodeEmoji("\ud83d\ude16")
    object TiredFace : UnicodeEmoji("\ud83d\ude2b")
    object Weary : UnicodeEmoji("\ud83d\ude29")
    object Triumph : UnicodeEmoji("\ud83d\ude24")
    object OpenMouth : UnicodeEmoji("\ud83d\ude2e")
    object Scream : UnicodeEmoji("\ud83d\ude31")
    object Fearful : UnicodeEmoji("\ud83d\ude28")
    object ColdSweat : UnicodeEmoji("\ud83d\ude30")
    object Hushed : UnicodeEmoji("\ud83d\ude2f")
    object Frowning : UnicodeEmoji("\ud83d\ude26")
    object Anguished : UnicodeEmoji("\ud83d\ude27")
    object Cry : UnicodeEmoji("\ud83d\ude22")
    object DisappointedRelieved : UnicodeEmoji("\ud83d\ude25")
    object Sleepy : UnicodeEmoji("\ud83d\ude2a")
    object Sweat : UnicodeEmoji("\ud83d\ude13")
    object Sob : UnicodeEmoji("\ud83d\ude2d")
    object DizzyFace : UnicodeEmoji("\ud83d\ude35")
    object Astonished : UnicodeEmoji("\ud83d\ude32")
    object ZipperMouth : UnicodeEmoji("\ud83e\udd10")
    object Mask : UnicodeEmoji("\ud83d\ude37")
    object ThermometerFace : UnicodeEmoji("\ud83e\udd12")
    object HeadBandage : UnicodeEmoji("\ud83e\udd15")
    object Sleeping : UnicodeEmoji("\ud83d\ude34")
    object Zzz : UnicodeEmoji("\ud83d\udca4")
    object Poop : UnicodeEmoji("\ud83d\udca9")
    object SmilingImp : UnicodeEmoji("\ud83d\ude08")
    object Imp : UnicodeEmoji("\ud83d\udc7f")
    object JapaneseOgre : UnicodeEmoji("\ud83d\udc79")
    object JapaneseGoblin : UnicodeEmoji("\ud83d\udc7a")
    object Skull : UnicodeEmoji("\ud83d\udc80")
    object Ghost : UnicodeEmoji("\ud83d\udc7b")
    object Alien : UnicodeEmoji("\ud83d\udc7d")
    object Robot : UnicodeEmoji("\ud83e\udd16")
    object SmileyCat : UnicodeEmoji("\ud83d\ude3a")
    object SmileCat : UnicodeEmoji("\ud83d\ude38")
    object JoyCat : UnicodeEmoji("\ud83d\ude39")
    object HeartEyesCat : UnicodeEmoji("\ud83d\ude3b")
    object SmirkCat : UnicodeEmoji("\ud83d\ude3c")
    object KissingCat : UnicodeEmoji("\ud83d\ude3d")
    object ScreamCat : UnicodeEmoji("\ud83d\ude40")
    object CryingCatFace : UnicodeEmoji("\ud83d\ude3f")
    object PoutingCat : UnicodeEmoji("\ud83d\ude3e")
    class RaisedHands(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\ude4c", tone)
    class Clap(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc4f", tone)
    class Wave(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc4b", tone)
    class Thumbsup(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc4d", tone)
    class Thumbsdown(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc4e", tone)
    class Punch(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc4a", tone)
    class Fist(tone: SkinTone? = null) : UnicodeEmoji("\u270a", tone)
    class V(tone: SkinTone? = null) : UnicodeEmoji("\u270c", tone)
    class OkHand(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc4c", tone)
    class RaisedHand(tone: SkinTone? = null) : UnicodeEmoji("\u270b", tone)
    class OpenHands(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc50", tone)
    class Muscle(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udcaa", tone)
    class Pray(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\ude4f", tone)
    class PointUp(tone: SkinTone? = null) : UnicodeEmoji("\u261d", tone)
    class PointUp2(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc46", tone)
    class PointDown(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc47", tone)
    class PointLeft(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc48", tone)
    class PointRight(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc49", tone)
    class MiddleFinger(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udd95", tone)
    class HandSplayed(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udd90", tone)
    class Metal(tone: SkinTone? = null) : UnicodeEmoji("\ud83e\udd18", tone)
    class Vulcan(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udd96", tone)
    class WritingHand(tone: SkinTone? = null) : UnicodeEmoji("\u270d", tone)
    class NailCare(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc85", tone)
    object Lips : UnicodeEmoji("\ud83d\udc44")
    object Tongue : UnicodeEmoji("\ud83d\udc45")
    class Ear(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc42", tone)
    class Nose(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc43", tone)
    object Eye : UnicodeEmoji("\ud83d\udc41")
    object Eyes : UnicodeEmoji("\ud83d\udc40")
    object BustInSilhouette : UnicodeEmoji("\ud83d\udc64")
    object BustsInSilhouette : UnicodeEmoji("\ud83d\udc65")
    object SpeakingHead : UnicodeEmoji("\ud83d\udde3")
    class Baby(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc76", tone)
    class Boy(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc66", tone)
    class Girl(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc67", tone)
    class Man(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc68", tone)
    class Woman(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc69", tone)
    class PersonWithBlondHair(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc71", tone)
    class OlderMan(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc74", tone)
    class OlderWoman(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc75", tone)
    class ManWithGuaPIMao(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc72", tone)
    class ManWithTurban(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc73", tone)
    class Cop(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc6e", tone)
    class ConstructionWorker(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc77", tone)
    class Guardsman(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc82", tone)
    class Spy(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udd75", tone)
    class Santa(tone: SkinTone? = null) : UnicodeEmoji("\ud83c\udf85", tone)
    class Angel(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc7c", tone)
    class Princess(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc78", tone)
    class BrideWithVeil(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc70", tone)
    class Walking(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udeb6", tone)
    class Running(tone: SkinTone? = null) : UnicodeEmoji("\ud83c\udfc3", tone)
    class Dancer(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc83", tone)
    object Dancers : UnicodeEmoji("\ud83d\udc6f")
    object Couple : UnicodeEmoji("\ud83d\udc6b")
    object TwoMenHoldingHands : UnicodeEmoji("\ud83d\udc6c")
    object TwoWomenHoldingHands : UnicodeEmoji("\ud83d\udc6d")
    class Bow(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\ude47", tone)
    class InformationDeskPerson(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc81", tone)
    class NoGood(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\ude45", tone)
    class OkWoman(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\ude46", tone)
    class RaisingHand(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\ude4b", tone)
    class PersonWithPoutingFace(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\ude4e", tone)
    class PersonFrowning(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\ude4d", tone)
    class Haircut(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc87", tone)
    class Massage(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udc86", tone)
    object CoupleWithHeart : UnicodeEmoji("\ud83d\udc91")
    object CoupleWW : UnicodeEmoji("\ud83d\udc69\u200d\u2764\ufe0f\u200d\ud83d\udc69")
    object CoupleMM : UnicodeEmoji("\ud83d\udc68\u200d\u2764\ufe0f\u200d\ud83d\udc68")
    object Couplekiss : UnicodeEmoji("\ud83d\udc8f")
    object KissWW : UnicodeEmoji("\ud83d\udc69\u200d\u2764\ufe0f\u200d\ud83d\udc8b\u200d\ud83d\udc69")
    object KissMM : UnicodeEmoji("\ud83d\udc68\u200d\u2764\ufe0f\u200d\ud83d\udc8b\u200d\ud83d\udc68")
    object Family : UnicodeEmoji("\ud83d\udc6a")
    object FamilyMwg : UnicodeEmoji("\ud83d\udc68\u200d\ud83d\udc69\u200d\ud83d\udc67")
    object FamilyMwgb : UnicodeEmoji("\ud83d\udc68\u200d\ud83d\udc69\u200d\ud83d\udc67\u200d\ud83d\udc66")
    object FamilyMwbb : UnicodeEmoji("\ud83d\udc68\u200d\ud83d\udc69\u200d\ud83d\udc66\u200d\ud83d\udc66")
    object FamilyMwgg : UnicodeEmoji("\ud83d\udc68\u200d\ud83d\udc69\u200d\ud83d\udc67\u200d\ud83d\udc67")
    object FamilyWwb : UnicodeEmoji("\ud83d\udc69\u200d\ud83d\udc69\u200d\ud83d\udc66")
    object FamilyWwg : UnicodeEmoji("\ud83d\udc69\u200d\ud83d\udc69\u200d\ud83d\udc67")
    object FamilyWwgb : UnicodeEmoji("\ud83d\udc69\u200d\ud83d\udc69\u200d\ud83d\udc67\u200d\ud83d\udc66")
    object FamilyWwbb : UnicodeEmoji("\ud83d\udc69\u200d\ud83d\udc69\u200d\ud83d\udc66\u200d\ud83d\udc66")
    object FamilyWwgg : UnicodeEmoji("\ud83d\udc69\u200d\ud83d\udc69\u200d\ud83d\udc67\u200d\ud83d\udc67")
    object FamilyMmb : UnicodeEmoji("\ud83d\udc68\u200d\ud83d\udc68\u200d\ud83d\udc66")
    object FamilyMmg : UnicodeEmoji("\ud83d\udc68\u200d\ud83d\udc68\u200d\ud83d\udc67")
    object FamilyMmgb : UnicodeEmoji("\ud83d\udc68\u200d\ud83d\udc68\u200d\ud83d\udc67\u200d\ud83d\udc66")
    object FamilyMmbb : UnicodeEmoji("\ud83d\udc68\u200d\ud83d\udc68\u200d\ud83d\udc66\u200d\ud83d\udc66")
    object FamilyMmgg : UnicodeEmoji("\ud83d\udc68\u200d\ud83d\udc68\u200d\ud83d\udc67\u200d\ud83d\udc67")
    object WomansClothes : UnicodeEmoji("\ud83d\udc5a")
    object Shirt : UnicodeEmoji("\ud83d\udc55")
    object Jeans : UnicodeEmoji("\ud83d\udc56")
    object Necktie : UnicodeEmoji("\ud83d\udc54")
    object Dress : UnicodeEmoji("\ud83d\udc57")
    object Bikini : UnicodeEmoji("\ud83d\udc59")
    object Kimono : UnicodeEmoji("\ud83d\udc58")
    object Lipstick : UnicodeEmoji("\ud83d\udc84")
    object Kiss : UnicodeEmoji("\ud83d\udc8b")
    object Footprints : UnicodeEmoji("\ud83d\udc63")
    object HighHeel : UnicodeEmoji("\ud83d\udc60")
    object Sandal : UnicodeEmoji("\ud83d\udc61")
    object Boot : UnicodeEmoji("\ud83d\udc62")
    object Shoe : UnicodeEmoji("\ud83d\udc5e")
    object AthleticShoe : UnicodeEmoji("\ud83d\udc5f")
    object WomansHat : UnicodeEmoji("\ud83d\udc52")
    object Tophat : UnicodeEmoji("\ud83c\udfa9")
    object HelmetWithCross : UnicodeEmoji("\u26d1")
    object MortarBoard : UnicodeEmoji("\ud83c\udf93")
    object Crown : UnicodeEmoji("\ud83d\udc51")
    object SchoolSatchel : UnicodeEmoji("\ud83c\udf92")
    object Pouch : UnicodeEmoji("\ud83d\udc5d")
    object Purse : UnicodeEmoji("\ud83d\udc5b")
    object Handbag : UnicodeEmoji("\ud83d\udc5c")
    object Briefcase : UnicodeEmoji("\ud83d\udcbc")
    object Eyeglasses : UnicodeEmoji("\ud83d\udc53")
    object DarkSunglasses : UnicodeEmoji("\ud83d\udd76")
    object Ring : UnicodeEmoji("\ud83d\udc8d")
    object ClosedUmbrella : UnicodeEmoji("\ud83c\udf02")
    object Cowboy : UnicodeEmoji("\ud83e\udd20")
    object Clown : UnicodeEmoji("\ud83e\udd21")
    object Sick : UnicodeEmoji("\ud83e\udd22")
    object Rofl : UnicodeEmoji("\ud83e\udd23")
    object Drool : UnicodeEmoji("\ud83e\udd24")
    object Lying : UnicodeEmoji("\ud83e\udd25")
    object Sneeze : UnicodeEmoji("\ud83e\udd27")
    class Prince(tone: SkinTone? = null) : UnicodeEmoji("\ud83e\udd34", tone)
    class ManInTuxedo(tone: SkinTone? = null) : UnicodeEmoji("\ud83e\udd35", tone)
    class MrsClaus(tone: SkinTone? = null) : UnicodeEmoji("\ud83e\udd36", tone)
    class Facepalm(tone: SkinTone? = null) : UnicodeEmoji("\ud83e\udd26", tone)
    class Shrug(tone: SkinTone? = null) : UnicodeEmoji("\ud83e\udd37", tone)
    class PregnantWoman(tone: SkinTone? = null) : UnicodeEmoji("\uD83E\uDD30", tone)
    class Selfie(tone: SkinTone? = null) : UnicodeEmoji("\ud83e\udd33", tone)
    class ManDancing(tone: SkinTone? = null) : UnicodeEmoji("\ud83d\udd7a", tone)
    class CallMe(tone: SkinTone? = null) : UnicodeEmoji("\ud83e\udd19", tone)
    class RaisedBackOfHand(tone: SkinTone? = null) : UnicodeEmoji("\ud83e\udd1a", tone)
    class LeftFist(tone: SkinTone? = null) : UnicodeEmoji("\ud83e\udd1e", tone)
    class RightFist(tone: SkinTone? = null) : UnicodeEmoji("\ud83e\udd1c", tone)
    class Handshake(tone: SkinTone? = null) : UnicodeEmoji("\ud83e\udd1d", tone)
    class FingersCrossed(tone: SkinTone? = null) : UnicodeEmoji("\ud83e\udd1e", tone)

    // Nature

    object Dog : UnicodeEmoji("\ud83d\udc36")
    object Cat : UnicodeEmoji("\ud83d\udc31")
    object Mouse : UnicodeEmoji("\ud83d\udc2d")
    object Hamster : UnicodeEmoji("\ud83d\udc39")
    object Rabbit : UnicodeEmoji("\ud83d\udc30")
    object Bear : UnicodeEmoji("\ud83d\udc3b")
    object PandaFace : UnicodeEmoji("\ud83d\udc3c")
    object Koala : UnicodeEmoji("\ud83d\udc28")
    object Tiger : UnicodeEmoji("\ud83d\udc2f")
    object LionFace : UnicodeEmoji("\ud83e\udd81")
    object Cow : UnicodeEmoji("\ud83d\udc2e")
    object Pig : UnicodeEmoji("\ud83d\udc37")
    object PigNose : UnicodeEmoji("\ud83d\udc3d")
    object Frog : UnicodeEmoji("\ud83d\udc38")
    object Octopus : UnicodeEmoji("\ud83d\udc19")
    object MonkeyFace : UnicodeEmoji("\ud83d\udc35")
    object SeeNoEvil : UnicodeEmoji("\ud83d\ude48")
    object HearNoEvil : UnicodeEmoji("\ud83d\ude49")
    object SpeakNoEvil : UnicodeEmoji("\ud83d\ude4a")
    object Monkey : UnicodeEmoji("\ud83d\udc12")
    object Chicken : UnicodeEmoji("\ud83d\udc14")
    object Penguin : UnicodeEmoji("\ud83d\udc27")
    object Bird : UnicodeEmoji("\ud83d\udc26")
    object BabyChick : UnicodeEmoji("\ud83d\udc24")
    object HatchingChick : UnicodeEmoji("\ud83d\udc23")
    object HatchedChick : UnicodeEmoji("\ud83d\udc25")
    object Wolf : UnicodeEmoji("\ud83d\udc3a")
    object Boar : UnicodeEmoji("\ud83d\udc17")
    object Horse : UnicodeEmoji("\ud83d\udc34")
    object Unicorn : UnicodeEmoji("\ud83e\udd84")
    object Bee : UnicodeEmoji("\ud83d\udc1d")
    object Bug : UnicodeEmoji("\ud83d\udc1b")
    object Snail : UnicodeEmoji("\ud83d\udc0c")
    object Beetle : UnicodeEmoji("\ud83d\udc1e")
    object Ant : UnicodeEmoji("\ud83d\udc1c")
    object Spider : UnicodeEmoji("\ud83d\udd77")
    object Scorpion : UnicodeEmoji("\ud83e\udd82")
    object Crab : UnicodeEmoji("\ud83e\udd80")
    object Snake : UnicodeEmoji("\ud83d\udc0d")
    object Turtle : UnicodeEmoji("\ud83d\udc22")
    object TropicalFish : UnicodeEmoji("\ud83d\udc20")
    object Fish : UnicodeEmoji("\ud83d\udc1f")
    object Blowfish : UnicodeEmoji("\ud83d\udc21")
    object Dolphin : UnicodeEmoji("\ud83d\udc2c")
    object Whale : UnicodeEmoji("\ud83d\udc33")
    object Whale2 : UnicodeEmoji("\ud83d\udc0b")
    object Crocodile : UnicodeEmoji("\ud83d\udc0a")
    object Leopard : UnicodeEmoji("\ud83d\udc06")
    object Tiger2 : UnicodeEmoji("\ud83d\udc05")
    object WaterBuffalo : UnicodeEmoji("\ud83d\udc03")
    object Ox : UnicodeEmoji("\ud83d\udc02")
    object Cow2 : UnicodeEmoji("\ud83d\udc04")
    object DromedaryCamel : UnicodeEmoji("\ud83d\udc2a")
    object Camel : UnicodeEmoji("\ud83d\udc2b")
    object Elephant : UnicodeEmoji("\ud83d\udc18")
    object Goat : UnicodeEmoji("\ud83d\udc10")
    object Ram : UnicodeEmoji("\ud83d\udc0f")
    object Sheep : UnicodeEmoji("\ud83d\udc11")
    object Racehorse : UnicodeEmoji("\ud83d\udc0e")
    object Pig2 : UnicodeEmoji("\ud83d\udc16")
    object Rat : UnicodeEmoji("\ud83d\udc00")
    object Mouse2 : UnicodeEmoji("\ud83d\udc01")
    object Rooster : UnicodeEmoji("\ud83d\udc13")
    object Turkey : UnicodeEmoji("\ud83e\udd83")
    object Dove : UnicodeEmoji("\ud83d\udd4a")
    object Dog2 : UnicodeEmoji("\ud83d\udc15")
    object Poodle : UnicodeEmoji("\ud83d\udc29")
    object Cat2 : UnicodeEmoji("\ud83d\udc08")
    object Rabbit2 : UnicodeEmoji("\ud83d\udc07")
    object Chipmunk : UnicodeEmoji("\ud83d\udc3f")
    object PawPrints : UnicodeEmoji("\ud83d\udc3e")
    object Dragon : UnicodeEmoji("\ud83d\udc09")
    object DragonFace : UnicodeEmoji("\ud83d\udc32")
    object Cactus : UnicodeEmoji("\ud83c\udf35")
    object ChristmasTree : UnicodeEmoji("\ud83c\udf84")
    object EvergreenTree : UnicodeEmoji("\ud83c\udf32")
    object DeciduousTree : UnicodeEmoji("\ud83c\udf33")
    object PalmTree : UnicodeEmoji("\ud83c\udf34")
    object Seedling : UnicodeEmoji("\ud83c\udf31")
    object Herb : UnicodeEmoji("\ud83c\udf3f")
    object Shamrock : UnicodeEmoji("\u2618")
    object FourLeafClover : UnicodeEmoji("\ud83c\udf40")
    object Bamboo : UnicodeEmoji("\ud83c\udf8d")
    object TanabataTree : UnicodeEmoji("\ud83c\udf8b")
    object Leaves : UnicodeEmoji("\ud83c\udf43")
    object FallenLeaf : UnicodeEmoji("\ud83c\udf42")
    object MapleLeaf : UnicodeEmoji("\ud83c\udf41")
    object EarOfRice : UnicodeEmoji("\ud83c\udf3e")
    object Hibiscus : UnicodeEmoji("\ud83c\udf3a")
    object Sunflower : UnicodeEmoji("\ud83c\udf3b")
    object Rose : UnicodeEmoji("\ud83c\udf39")
    object Tulip : UnicodeEmoji("\ud83c\udf37")
    object Blossom : UnicodeEmoji("\ud83c\udf3c")
    object CherryBlossom : UnicodeEmoji("\ud83c\udf38")
    object Bouquet : UnicodeEmoji("\ud83d\udc90")
    object Mushroom : UnicodeEmoji("\ud83c\udf44")
    object Chestnut : UnicodeEmoji("\ud83c\udf30")
    object JackOLantern : UnicodeEmoji("\ud83c\udf83")
    object Shell : UnicodeEmoji("\ud83d\udc1a")
    object SpiderWeb : UnicodeEmoji("\ud83d\udd78")
    object EarthAmericas : UnicodeEmoji("\ud83c\udf0e")
    object EarthAfrica : UnicodeEmoji("\ud83c\udf0d")
    object EarthAsia : UnicodeEmoji("\ud83c\udf0f")
    object FullMoon : UnicodeEmoji("\ud83c\udf15")
    object WaningGibbousMoon : UnicodeEmoji("\ud83c\udf16")
    object LastQuarterMoon : UnicodeEmoji("\ud83c\udf17")
    object WaningCrescentMoon : UnicodeEmoji("\ud83c\udf18")
    object NewMoon : UnicodeEmoji("\ud83c\udf11")
    object WaxingCrescentMoon : UnicodeEmoji("\ud83c\udf12")
    object FirstQuarterMoon : UnicodeEmoji("\ud83c\udf13")
    object Moon : UnicodeEmoji("\ud83c\udf14")
    object NewMoonWithFace : UnicodeEmoji("\ud83c\udf1a")
    object FullMoonWithFace : UnicodeEmoji("\ud83c\udf1d")
    object FirstQuarterMoonWithFace : UnicodeEmoji("\ud83c\udf1b")
    object LastQuarterMoonWithFace : UnicodeEmoji("\ud83c\udf1c")
    object SunWithFace : UnicodeEmoji("\ud83c\udf1e")
    object CrescentMoon : UnicodeEmoji("\ud83c\udf19")
    object Star : UnicodeEmoji("\u2b50")
    object Star2 : UnicodeEmoji("\ud83c\udf1f")
    object Dizzy : UnicodeEmoji("\ud83d\udcab")
    object Sparkles : UnicodeEmoji("\u2728")
    object Comet : UnicodeEmoji("\u2604")
    object Sunny : UnicodeEmoji("\u2600")
    object WhiteSunSmallCloud : UnicodeEmoji("\ud83c\udf24")
    object PartlySunny : UnicodeEmoji("\u26c5")
    object WhiteSunCloud : UnicodeEmoji("\ud83c\udf25")
    object WhiteSunRainCloud : UnicodeEmoji("\ud83c\udf26")
    object Cloud : UnicodeEmoji("\u2601")
    object CloudRain : UnicodeEmoji("\ud83c\udf27")
    object ThunderCloudRain : UnicodeEmoji("\u26c8")
    object CloudLightning : UnicodeEmoji("\ud83c\udf29")
    object Zap : UnicodeEmoji("\u26a1")
    object Fire : UnicodeEmoji("\ud83d\udd25")
    object Boom : UnicodeEmoji("\ud83d\udca5")
    object Snowflake : UnicodeEmoji("\u2744")
    object CloudSnow : UnicodeEmoji("\ud83c\udf28")
    object Snowman2 : UnicodeEmoji("\u2603")
    object Snowman : UnicodeEmoji("\u26c4")
    object WindBlowingFace : UnicodeEmoji("\ud83c\udf2c")
    object Dash : UnicodeEmoji("\ud83d\udca8")
    object CloudTornado : UnicodeEmoji("\ud83c\udf2a")
    object Fog : UnicodeEmoji("\ud83c\udf2b")
    object Umbrella2 : UnicodeEmoji("\u2602")
    object Umbrella : UnicodeEmoji("\u2614")
    object Droplet : UnicodeEmoji("\ud83d\udca7")
    object SweatDrops : UnicodeEmoji("\ud83d\udca6")
    object Ocean : UnicodeEmoji("\ud83c\udf0a")
    object Eagle : UnicodeEmoji("\ud83e\udd85")
    object Duck : UnicodeEmoji("\ud83e\udd86")
    object Bat : UnicodeEmoji("\ud83e\udd87")
    object Shark : UnicodeEmoji("\ud83e\udd88")
    object Owl : UnicodeEmoji("\ud83e\udd89")
    object Fox : UnicodeEmoji("\ud83e\udd8a")
    object Butterfly : UnicodeEmoji("\ud83e\udd8b")
    object Deer : UnicodeEmoji("\ud83e\udd8c")
    object Gorilla : UnicodeEmoji("\ud83e\udd8d")
    object Lizard : UnicodeEmoji("\ud83e\udd8e")
    object Rhino : UnicodeEmoji("\ud83e\udd8f")
    object WiltedFlower : UnicodeEmoji("\ud83e\udd40")
    object Shrimp : UnicodeEmoji("\ud83e\udd90")
    object Squid : UnicodeEmoji("\ud83e\udd91")

    // Food

    object GreenApple : UnicodeEmoji("\ud83c\udf4f")
    object Apple : UnicodeEmoji("\ud83c\udf4e")
    object Pear : UnicodeEmoji("\ud83c\udf50")
    object Tangerine : UnicodeEmoji("\ud83c\udf4a")
    object Lemon : UnicodeEmoji("\ud83c\udf4b")
    object Banana : UnicodeEmoji("\ud83c\udf4c")
    object Watermelon : UnicodeEmoji("\ud83c\udf49")
    object Grapes : UnicodeEmoji("\ud83c\udf47")
    object Strawberry : UnicodeEmoji("\ud83c\udf53")
    object Melon : UnicodeEmoji("\ud83c\udf48")
    object Cherries : UnicodeEmoji("\ud83c\udf52")
    object Peach : UnicodeEmoji("\ud83c\udf51")
    object Pineapple : UnicodeEmoji("\ud83c\udf4d")
    object Tomato : UnicodeEmoji("\ud83c\udf45")
    object Eggplant : UnicodeEmoji("\ud83c\udf46")
    object HotPepper : UnicodeEmoji("\ud83c\udf36")
    object Corn : UnicodeEmoji("\ud83c\udf3d")
    object SweetPotato : UnicodeEmoji("\ud83c\udf60")
    object HoneyPot : UnicodeEmoji("\ud83c\udf6f")
    object Bread : UnicodeEmoji("\ud83c\udf5e")
    object Cheese : UnicodeEmoji("\ud83e\uddc0")
    object PoultryLeg : UnicodeEmoji("\ud83c\udf57")
    object MeatOnBone : UnicodeEmoji("\ud83c\udf56")
    object FriedShrimp : UnicodeEmoji("\ud83c\udf64")
    object Cooking : UnicodeEmoji("\ud83c\udf73")
    object Hamburger : UnicodeEmoji("\ud83c\udf54")
    object Fries : UnicodeEmoji("\ud83c\udf5f")
    object Hotdog : UnicodeEmoji("\ud83c\udf2d")
    object Pizza : UnicodeEmoji("\ud83c\udf55")
    object Spaghetti : UnicodeEmoji("\ud83c\udf5d")
    object Taco : UnicodeEmoji("\ud83c\udf2e")
    object Burrito : UnicodeEmoji("\ud83c\udf2f")
    object Ramen : UnicodeEmoji("\ud83c\udf5c")
    object Stew : UnicodeEmoji("\ud83c\udf72")
    object FishCake : UnicodeEmoji("\ud83c\udf65")
    object Sushi : UnicodeEmoji("\ud83c\udf63")
    object Bento : UnicodeEmoji("\ud83c\udf71")
    object Curry : UnicodeEmoji("\ud83c\udf5b")
    object RiceBall : UnicodeEmoji("\ud83c\udf59")
    object Rice : UnicodeEmoji("\ud83c\udf5a")
    object RiceCracker : UnicodeEmoji("\ud83c\udf58")
    object Oden : UnicodeEmoji("\ud83c\udf62")
    object Dango : UnicodeEmoji("\ud83c\udf61")
    object ShavedIce : UnicodeEmoji("\ud83c\udf67")
    object IceCream : UnicodeEmoji("\ud83c\udf66")
    object Cake : UnicodeEmoji("\ud83c\udf70")
    object Birthday : UnicodeEmoji("\ud83c\udf82")
    object Custard : UnicodeEmoji("\ud83c\udf6e")
    object Candy : UnicodeEmoji("\ud83c\udf6c")
    object Lollipop : UnicodeEmoji("\ud83c\udf6d")
    object ChocolateBar : UnicodeEmoji("\ud83c\udf6b")
    object Popcorn : UnicodeEmoji("\ud83c\udf7f")
    object Doughnut : UnicodeEmoji("\ud83c\udf69")
    object Cookie : UnicodeEmoji("\ud83c\udf6a")
    object Beer : UnicodeEmoji("\ud83c\udf7a")
    object Beers : UnicodeEmoji("\ud83c\udf7b")
    object WineGlass : UnicodeEmoji("\ud83c\udf77")
    object Cocktail : UnicodeEmoji("\ud83c\udf78")
    object TropicalDrink : UnicodeEmoji("\ud83c\udf79")
    object Champagne : UnicodeEmoji("\ud83c\udf7e")
    object Sake : UnicodeEmoji("\ud83c\udf76")
    object Tea : UnicodeEmoji("\ud83c\udf75")
    object Coffee : UnicodeEmoji("\u2615")
    object BabyBottle : UnicodeEmoji("\ud83c\udf7c")
    object ForkAndKnife : UnicodeEmoji("\ud83c\udf74")
    object ForkKnifePlate : UnicodeEmoji("\ud83c\udf7d")
    object Croissant : UnicodeEmoji("\ud83e\udd50")
    object Avocado : UnicodeEmoji("\ud83e\udd51")
    object Cucumber : UnicodeEmoji("\ud83e\udd52")
    object Bacon : UnicodeEmoji("\ud83e\udd53")
    object Potato : UnicodeEmoji("\ud83e\udd54")
    object Carrot : UnicodeEmoji("\ud83e\udd55")
    object FrenchBread : UnicodeEmoji("\ud83e\udd56")
    object Salad : UnicodeEmoji("\ud83e\udd57")
    object Paella : UnicodeEmoji("\ud83e\udd58")
    object StuffedFlatbread : UnicodeEmoji("\ud83e\udd59")
    object ClinkingGlass : UnicodeEmoji("\ud83e\udd42")
    object Whisky : UnicodeEmoji("\ud83e\udd43")
    object Spoon : UnicodeEmoji("\ud83e\udd44")
    object Egg : UnicodeEmoji("\ud83e\udd5a")
    object Milk : UnicodeEmoji("\ud83e\udd5b")
    object Peanuts : UnicodeEmoji("\ud83e\udd5c")
    object Kiwi : UnicodeEmoji("\ud83e\udd5d")
    object Pancakes : UnicodeEmoji("\ud83e\udd5e")

    // Activities

    object Soccer : UnicodeEmoji("\u26bd")
    object Basketball : UnicodeEmoji("\ud83c\udfc0")
    object Football : UnicodeEmoji("\ud83c\udfc8")
    object Baseball : UnicodeEmoji("\u26be")
    object Tennis : UnicodeEmoji("\ud83c\udfbe")
    object Volleyball : UnicodeEmoji("\ud83c\udfd0")
    object RugbyFootball : UnicodeEmoji("\ud83c\udfc9")
    object EightBall : UnicodeEmoji("\ud83c\udfb1")
    object Golf : UnicodeEmoji("\u26f3")
    object Golfer : UnicodeEmoji("\ud83c\udfcc")
    object PingPong : UnicodeEmoji("\ud83c\udfd3")
    object Badminton : UnicodeEmoji("\ud83c\udff8")
    object Hockey : UnicodeEmoji("\ud83c\udfd2")
    object FieldHockey : UnicodeEmoji("\ud83c\udfd1")
    object Cricket : UnicodeEmoji("\ud83c\udfcf")
    object Ski : UnicodeEmoji("\ud83c\udfbf")
    object Skier : UnicodeEmoji("\u26f7")
    object Snowboarder : UnicodeEmoji("\ud83c\udfc2")
    object IceSkate : UnicodeEmoji("\u26f8")
    object BowAndArrow : UnicodeEmoji("\ud83c\udff9")
    object FishingPoleAndFish : UnicodeEmoji("\ud83c\udfa3")
    object Rowboat : UnicodeEmoji("\ud83d\udea3")
    object Swimmer : UnicodeEmoji("\ud83c\udfca")
    object Surfer : UnicodeEmoji("\ud83c\udfc4")
    object Bath : UnicodeEmoji("\ud83d\udec0")
    object BasketballPlayer : UnicodeEmoji("\u26f9")
    object Lifter : UnicodeEmoji("\ud83c\udfcb")
    object Bicyclist : UnicodeEmoji("\ud83d\udeb4")
    object MountainBicyclist : UnicodeEmoji("\ud83d\udeb5")
    object HorseRacing : UnicodeEmoji("\ud83c\udfc7")
    object Levitate : UnicodeEmoji("\ud83d\udd74")
    object Trophy : UnicodeEmoji("\ud83c\udfc6")
    object RunningShirtWithSash : UnicodeEmoji("\ud83c\udfbd")
    object Medal : UnicodeEmoji("\ud83c\udfc5")
    object MilitaryMedal : UnicodeEmoji("\ud83c\udf96")
    object ReminderRibbon : UnicodeEmoji("\ud83c\udf97")
    object Rosette : UnicodeEmoji("\ud83c\udff5")
    object Ticket : UnicodeEmoji("\ud83c\udfab")
    object Tickets : UnicodeEmoji("\ud83c\udf9f")
    object PerformingArts : UnicodeEmoji("\ud83c\udfad")
    object Art : UnicodeEmoji("\ud83c\udfa8")
    object CircusTent : UnicodeEmoji("\ud83c\udfaa")
    object Microphone : UnicodeEmoji("\ud83c\udfa4")
    object Headphones : UnicodeEmoji("\ud83c\udfa7")
    object MusicalScore : UnicodeEmoji("\ud83c\udfbc")
    object MusicalKeyboard : UnicodeEmoji("\ud83c\udfb9")
    object Saxophone : UnicodeEmoji("\ud83c\udfb7")
    object Trumpet : UnicodeEmoji("\ud83c\udfba")
    object Guitar : UnicodeEmoji("\ud83c\udfb8")
    object Violin : UnicodeEmoji("\ud83c\udfbb")
    object Clapper : UnicodeEmoji("\ud83c\udfac")
    object VideoGame : UnicodeEmoji("\ud83c\udfae")
    object SpaceInvader : UnicodeEmoji("\ud83d\udc7e")
    object Dart : UnicodeEmoji("\ud83c\udfaf")
    object GameDie : UnicodeEmoji("\ud83c\udfb2")
    object SlotMachine : UnicodeEmoji("\ud83c\udfb0")
    object Bowling : UnicodeEmoji("\ud83c\udfb3")
    object Cartwheel : UnicodeEmoji("\ud83e\udd38")
    object Juggling : UnicodeEmoji("\ud83e\udd39")
    object Wrestlers : UnicodeEmoji("\ud83e\udd3c")
    object BoxingGlove : UnicodeEmoji("\ud83e\udd4a")
    object MartialArtsUniform : UnicodeEmoji("\ud83e\udd4b")
    object WaterPolo : UnicodeEmoji("\ud83e\udd3d")
    object Handball : UnicodeEmoji("\ud83e\udd3e")
    object Goal : UnicodeEmoji("\ud83e\udd45")
    object Fencer : UnicodeEmoji("\ud83e\udd3a")
    object FirstPlace : UnicodeEmoji("\ud83e\udd47")
    object SecondPlace : UnicodeEmoji("\ud83e\udd48")
    object ThirdPlace : UnicodeEmoji("\ud83e\udd49")
    object Drum : UnicodeEmoji("\ud83e\udd41")

    // Travel

    object Car : UnicodeEmoji("\ud83d\ude97")
    object Taxi : UnicodeEmoji("\ud83d\ude95")
    object BlueCar : UnicodeEmoji("\ud83d\ude99")
    object Bus : UnicodeEmoji("\ud83d\ude8c")
    object Trolleybus : UnicodeEmoji("\ud83d\ude8e")
    object RaceCar : UnicodeEmoji("\ud83c\udfce")
    object PoliceCar : UnicodeEmoji("\ud83d\ude93")
    object Ambulance : UnicodeEmoji("\ud83d\ude91")
    object FireEngine : UnicodeEmoji("\ud83d\ude92")
    object Minibus : UnicodeEmoji("\ud83d\ude90")
    object Truck : UnicodeEmoji("\ud83d\ude9a")
    object ArticulatedLorry : UnicodeEmoji("\ud83d\ude9b")
    object Tractor : UnicodeEmoji("\ud83d\ude9c")
    object Motorcycle : UnicodeEmoji("\ud83c\udfcd")
    object Bike : UnicodeEmoji("\ud83d\udeb2")
    object RotatingLight : UnicodeEmoji("\ud83d\udea8")
    object OncomingPoliceCar : UnicodeEmoji("\ud83d\ude94")
    object OncomingBus : UnicodeEmoji("\ud83d\ude8d")
    object OncomingAutomobile : UnicodeEmoji("\ud83d\ude98")
    object OncomingTaxi : UnicodeEmoji("\ud83d\ude96")
    object AerialTramway : UnicodeEmoji("\ud83d\udea1")
    object MountainCableway : UnicodeEmoji("\ud83d\udea0")
    object SuspensionRailway : UnicodeEmoji("\ud83d\ude9f")
    object RailwayCar : UnicodeEmoji("\ud83d\ude83")
    object Train : UnicodeEmoji("\ud83d\ude8b")
    object Monorail : UnicodeEmoji("\ud83d\ude9d")
    object BullettrainSide : UnicodeEmoji("\ud83d\ude84")
    object BullettrainFront : UnicodeEmoji("\ud83d\ude85")
    object LightRail : UnicodeEmoji("\ud83d\ude88")
    object MountainRailway : UnicodeEmoji("\ud83d\ude9e")
    object SteamLocomotive : UnicodeEmoji("\ud83d\ude82")
    object Train2 : UnicodeEmoji("\ud83d\ude86")
    object Metro : UnicodeEmoji("\ud83d\ude87")
    object Tram : UnicodeEmoji("\ud83d\ude8a")
    object Station : UnicodeEmoji("\ud83d\ude89")
    object Helicopter : UnicodeEmoji("\ud83d\ude81")
    object AirplaneSmall : UnicodeEmoji("\ud83d\udee9")
    object Airplane : UnicodeEmoji("\u2708")
    object AirplaneDeparture : UnicodeEmoji("\ud83d\udeeb")
    object AirplaneArriving : UnicodeEmoji("\ud83d\udeec")
    object Sailboat : UnicodeEmoji("\u26f5")
    object Motorboat : UnicodeEmoji("\ud83d\udee5")
    object Speedboat : UnicodeEmoji("\ud83d\udea4")
    object Ferry : UnicodeEmoji("\u26f4")
    object CruiseShip : UnicodeEmoji("\ud83d\udef3")
    object Rocket : UnicodeEmoji("\ud83d\ude80")
    object SatelliteOrbital : UnicodeEmoji("\ud83d\udef0")
    object Seat : UnicodeEmoji("\ud83d\udcba")
    object Anchor : UnicodeEmoji("\u2693")
    object Construction : UnicodeEmoji("\ud83d\udea7")
    object Fuelpump : UnicodeEmoji("\u26fd")
    object Busstop : UnicodeEmoji("\ud83d\ude8f")
    object VerticalTrafficLight : UnicodeEmoji("\ud83d\udea6")
    object TrafficLight : UnicodeEmoji("\ud83d\udea5")
    object CheckeredFlag : UnicodeEmoji("\ud83c\udfc1")
    object Ship : UnicodeEmoji("\ud83d\udea2")
    object FerrisWheel : UnicodeEmoji("\ud83c\udfa1")
    object RollerCoaster : UnicodeEmoji("\ud83c\udfa2")
    object CarouselHorse : UnicodeEmoji("\ud83c\udfa0")
    object ConstructionSite : UnicodeEmoji("\ud83c\udfd7")
    object Foggy : UnicodeEmoji("\ud83c\udf01")
    object TokyoTower : UnicodeEmoji("\ud83d\uddfc")
    object Factory : UnicodeEmoji("\ud83c\udfed")
    object Fountain : UnicodeEmoji("\u26f2")
    object RiceScene : UnicodeEmoji("\ud83c\udf91")
    object Mountain : UnicodeEmoji("\u26f0")
    object MountainSnow : UnicodeEmoji("\ud83c\udfd4")
    object MountFuji : UnicodeEmoji("\ud83d\uddfb")
    object Volcano : UnicodeEmoji("\ud83c\udf0b")
    object Japan : UnicodeEmoji("\ud83d\uddfe")
    object Camping : UnicodeEmoji("\ud83c\udfd5")
    object Tent : UnicodeEmoji("\u26fa")
    object Park : UnicodeEmoji("\ud83c\udfde")
    object Motorway : UnicodeEmoji("\ud83d\udee3")
    object RailwayTrack : UnicodeEmoji("\ud83d\udee4")
    object Sunrise : UnicodeEmoji("\ud83c\udf05")
    object SunriseOverMountains : UnicodeEmoji("\ud83c\udf04")
    object Desert : UnicodeEmoji("\ud83c\udfdc")
    object Beach : UnicodeEmoji("\ud83c\udfd6")
    object Island : UnicodeEmoji("\ud83c\udfdd")
    object CitySunrise : UnicodeEmoji("\ud83c\udf07")
    object CityDusk : UnicodeEmoji("\ud83c\udf06")
    object Cityscape : UnicodeEmoji("\ud83c\udfd9")
    object NightWithStars : UnicodeEmoji("\ud83c\udf03")
    object BridgeAtNight : UnicodeEmoji("\ud83c\udf09")
    object MilkyWay : UnicodeEmoji("\ud83c\udf0c")
    object Stars : UnicodeEmoji("\ud83c\udf20")
    object Sparkler : UnicodeEmoji("\ud83c\udf87")
    object Fireworks : UnicodeEmoji("\ud83c\udf86")
    object Rainbow : UnicodeEmoji("\ud83c\udf08")
    object Homes : UnicodeEmoji("\ud83c\udfd8")
    object EuropeanCastle : UnicodeEmoji("\ud83c\udff0")
    object JapaneseCastle : UnicodeEmoji("\ud83c\udfef")
    object Stadium : UnicodeEmoji("\ud83c\udfdf")
    object StatueOfLiberty : UnicodeEmoji("\ud83d\uddfd")
    object House : UnicodeEmoji("\ud83c\udfe0")
    object HouseWithGarden : UnicodeEmoji("\ud83c\udfe1")
    object HouseAbandoned : UnicodeEmoji("\ud83c\udfda")
    object Office : UnicodeEmoji("\ud83c\udfe2")
    object DepartmentStore : UnicodeEmoji("\ud83c\udfec")
    object PostOffice : UnicodeEmoji("\ud83c\udfe3")
    object EuropeanPostOffice : UnicodeEmoji("\ud83c\udfe4")
    object Hospital : UnicodeEmoji("\ud83c\udfe5")
    object Bank : UnicodeEmoji("\ud83c\udfe6")
    object Hotel : UnicodeEmoji("\ud83c\udfe8")
    object ConvenienceStore : UnicodeEmoji("\ud83c\udfea")
    object School : UnicodeEmoji("\ud83c\udfeb")
    object LoveHotel : UnicodeEmoji("\ud83c\udfe9")
    object Wedding : UnicodeEmoji("\ud83d\udc92")
    object ClassicalBuilding : UnicodeEmoji("\ud83c\udfdb")
    object Church : UnicodeEmoji("\u26ea")
    object Mosque : UnicodeEmoji("\ud83d\udd4c")
    object Synagogue : UnicodeEmoji("\ud83d\udd4d")
    object Kaaba : UnicodeEmoji("\ud83d\udd4b")
    object ShintoShrine : UnicodeEmoji("\u26e9")
    object Scooter : UnicodeEmoji("\ud83d\udef4")
    object Motorbike : UnicodeEmoji("\ud83d\udef5")
    object Canoe : UnicodeEmoji("\ud83d\udef6")

    // Objects

    object Watch : UnicodeEmoji("\u231a")
    object Iphone : UnicodeEmoji("\ud83d\udcf1")
    object Calling : UnicodeEmoji("\ud83d\udcf2")
    object Computer : UnicodeEmoji("\ud83d\udcbb")
    object Keyboard : UnicodeEmoji("\u2328")
    object Desktop : UnicodeEmoji("\ud83d\udda5")
    object Printer : UnicodeEmoji("\ud83d\udda8")
    object MouseThreeButton : UnicodeEmoji("\ud83d\uddb1")
    object Trackball : UnicodeEmoji("\ud83d\uddb2")
    object Joystick : UnicodeEmoji("\ud83d\udd79")
    object Compression : UnicodeEmoji("\ud83d\udddc")
    object Minidisc : UnicodeEmoji("\ud83d\udcbd")
    object FloppyDisk : UnicodeEmoji("\ud83d\udcbe")
    object CD : UnicodeEmoji("\ud83d\udcbf")
    object Dvd : UnicodeEmoji("\ud83d\udcc0")
    object Vhs : UnicodeEmoji("\ud83d\udcfc")
    object Camera : UnicodeEmoji("\ud83d\udcf7")
    object CameraWithFlash : UnicodeEmoji("\ud83d\udcf8")
    object VideoCamera : UnicodeEmoji("\ud83d\udcf9")
    object MovieCamera : UnicodeEmoji("\ud83c\udfa5")
    object Projector : UnicodeEmoji("\ud83d\udcfd")
    object FilmFrames : UnicodeEmoji("\ud83c\udf9e")
    object TelephoneReceiver : UnicodeEmoji("\ud83d\udcde")
    object Telephone : UnicodeEmoji("\u260e")
    object Pager : UnicodeEmoji("\ud83d\udcdf")
    object Fax : UnicodeEmoji("\ud83d\udce0")
    object TV : UnicodeEmoji("\ud83d\udcfa")
    object Radio : UnicodeEmoji("\ud83d\udcfb")
    object Microphone2 : UnicodeEmoji("\ud83c\udf99")
    object LevelSlider : UnicodeEmoji("\ud83c\udf9a")
    object ControlKnobs : UnicodeEmoji("\ud83c\udf9b")
    object Stopwatch : UnicodeEmoji("\u23f1")
    object Timer : UnicodeEmoji("\u23f2")
    object AlarmClock : UnicodeEmoji("\u23f0")
    object Clock : UnicodeEmoji("\ud83d\udd70")
    object HourglassFlowingSand : UnicodeEmoji("\u23f3")
    object Hourglass : UnicodeEmoji("\u231b")
    object Satellite : UnicodeEmoji("\ud83d\udce1")
    object Battery : UnicodeEmoji("\ud83d\udd0b")
    object ElectricPlug : UnicodeEmoji("\ud83d\udd0c")
    object Bulb : UnicodeEmoji("\ud83d\udca1")
    object Flashlight : UnicodeEmoji("\ud83d\udd26")
    object Candle : UnicodeEmoji("\ud83d\udd6f")
    object Wastebasket : UnicodeEmoji("\ud83d\uddd1")
    object Oil : UnicodeEmoji("\ud83d\udee2")
    object MoneyWithWings : UnicodeEmoji("\ud83d\udcb8")
    object Dollar : UnicodeEmoji("\ud83d\udcb5")
    object Yen : UnicodeEmoji("\ud83d\udcb4")
    object Euro : UnicodeEmoji("\ud83d\udcb6")
    object Pound : UnicodeEmoji("\ud83d\udcb7")
    object Moneybag : UnicodeEmoji("\ud83d\udcb0")
    object CreditCard : UnicodeEmoji("\ud83d\udcb3")
    object Gem : UnicodeEmoji("\ud83d\udc8e")
    object Scales : UnicodeEmoji("\u2696")
    object Wrench : UnicodeEmoji("\ud83d\udd27")
    object Hammer : UnicodeEmoji("\ud83d\udd28")
    object HammerPick : UnicodeEmoji("\u2692")
    object Tools : UnicodeEmoji("\ud83d\udee0")
    object Pick : UnicodeEmoji("\u26cf")
    object NutAndBolt : UnicodeEmoji("\ud83d\udd29")
    object Gear : UnicodeEmoji("\u2699")
    object Chains : UnicodeEmoji("\u26d3")
    object Gun : UnicodeEmoji("\ud83d\udd2b")
    object Bomb : UnicodeEmoji("\ud83d\udca3")
    object Knife : UnicodeEmoji("\ud83d\udd2a")
    object Dagger : UnicodeEmoji("\ud83d\udde1")
    object CrossedSwords : UnicodeEmoji("\u2694")
    object Shield : UnicodeEmoji("\ud83d\udee1")
    object Smoking : UnicodeEmoji("\ud83d\udeac")
    object SkullCrossbones : UnicodeEmoji("\u2620")
    object Coffin : UnicodeEmoji("\u26b0")
    object Urn : UnicodeEmoji("\u26b1")
    object Amphora : UnicodeEmoji("\ud83c\udffa")
    object CrystalBall : UnicodeEmoji("\ud83d\udd2e")
    object PrayerBeads : UnicodeEmoji("\ud83d\udcff")
    object Barber : UnicodeEmoji("\ud83d\udc88")
    object Alembic : UnicodeEmoji("\u2697")
    object Telescope : UnicodeEmoji("\ud83d\udd2d")
    object Microscope : UnicodeEmoji("\ud83d\udd2c")
    object Hole : UnicodeEmoji("\ud83d\udd73")
    object Pill : UnicodeEmoji("\ud83d\udc8a")
    object Syringe : UnicodeEmoji("\ud83d\udc89")
    object Thermometer : UnicodeEmoji("\ud83c\udf21")
    object Label : UnicodeEmoji("\ud83c\udff7")
    object Bookmark : UnicodeEmoji("\ud83d\udd16")
    object Toilet : UnicodeEmoji("\ud83d\udebd")
    object Shower : UnicodeEmoji("\ud83d\udebf")
    object Bathtub : UnicodeEmoji("\ud83d\udec1")
    object Key : UnicodeEmoji("\ud83d\udd11")
    object Key2 : UnicodeEmoji("\ud83d\udddd")
    object Couch : UnicodeEmoji("\ud83d\udecb")
    object SleepingAccommodation : UnicodeEmoji("\ud83d\udecc")
    object Bed : UnicodeEmoji("\ud83d\udecf")
    object Door : UnicodeEmoji("\ud83d\udeaa")
    object Bellhop : UnicodeEmoji("\ud83d\udece")
    object FramePhoto : UnicodeEmoji("\ud83d\uddbc")
    object Map : UnicodeEmoji("\ud83d\uddfa")
    object BeachUmbrella : UnicodeEmoji("\u26f1")
    object Moyai : UnicodeEmoji("\ud83d\uddff")
    object ShoppingBags : UnicodeEmoji("\ud83d\udecd")
    object Balloon : UnicodeEmoji("\ud83c\udf88")
    object Flags : UnicodeEmoji("\ud83c\udf8f")
    object Ribbon : UnicodeEmoji("\ud83c\udf80")
    object Gift : UnicodeEmoji("\ud83c\udf81")
    object ConfettiBall : UnicodeEmoji("\ud83c\udf8a")
    object Tada : UnicodeEmoji("\ud83c\udf89")
    object Dolls : UnicodeEmoji("\ud83c\udf8e")
    object WindChime : UnicodeEmoji("\ud83c\udf90")
    object CrossedFlags : UnicodeEmoji("\ud83c\udf8c")
    object Lantern : UnicodeEmoji("\ud83c\udfee")
    object Envelope : UnicodeEmoji("\u2709")
    object Email : UnicodeEmoji("\ud83d\udce7")
    object EnvelopeWithArrow : UnicodeEmoji("\ud83d\udce9")
    object IncomingEnvelope : UnicodeEmoji("\ud83d\udce8")
    object LoveLetter : UnicodeEmoji("\ud83d\udc8c")
    object Postbox : UnicodeEmoji("\ud83d\udcee")
    object MailboxClosed : UnicodeEmoji("\ud83d\udcea")
    object Mailbox : UnicodeEmoji("\ud83d\udceb")
    object MailboxWithMail : UnicodeEmoji("\ud83d\udcec")
    object MailboxWithNoMail : UnicodeEmoji("\ud83d\udced")
    object Package : UnicodeEmoji("\ud83d\udce6")
    object PostalHorn : UnicodeEmoji("\ud83d\udcef")
    object InboxTray : UnicodeEmoji("\ud83d\udce5")
    object OutboxTray : UnicodeEmoji("\ud83d\udce4")
    object Scroll : UnicodeEmoji("\ud83d\udcdc")
    object PageWithCurl : UnicodeEmoji("\ud83d\udcc3")
    object BookmarkTabs : UnicodeEmoji("\ud83d\udcd1")
    object BarChart : UnicodeEmoji("\ud83d\udcca")
    object ChartWithUpwardsTrend : UnicodeEmoji("\ud83d\udcc8")
    object ChartWithDownwardsTrend : UnicodeEmoji("\ud83d\udcc9")
    object PageFacingUp : UnicodeEmoji("\ud83d\udcc4")
    object Date : UnicodeEmoji("\ud83d\udcc5")
    object Calendar : UnicodeEmoji("\ud83d\udcc6")
    object CalendarSpiral : UnicodeEmoji("\ud83d\uddd3")
    object CardIndex : UnicodeEmoji("\ud83d\udcc7")
    object CardBox : UnicodeEmoji("\ud83d\uddc3")
    object BallotBox : UnicodeEmoji("\ud83d\uddf3")
    object FileCabinet : UnicodeEmoji("\ud83d\uddc4")
    object Clipboard : UnicodeEmoji("\ud83d\udccb")
    object NotepadSpiral : UnicodeEmoji("\ud83d\uddd2")
    object FileFolder : UnicodeEmoji("\ud83d\udcc1")
    object OpenFileFolder : UnicodeEmoji("\ud83d\udcc2")
    object Dividers : UnicodeEmoji("\ud83d\uddc2")
    object Newspaper2 : UnicodeEmoji("\ud83d\uddde")
    object Newspaper : UnicodeEmoji("\ud83d\udcf0")
    object Notebook : UnicodeEmoji("\ud83d\udcd3")
    object ClosedBook : UnicodeEmoji("\ud83d\udcd5")
    object GreenBook : UnicodeEmoji("\ud83d\udcd7")
    object BlueBook : UnicodeEmoji("\ud83d\udcd8")
    object OrangeBook : UnicodeEmoji("\ud83d\udcd9")
    object NotebookWithDecorativeCover : UnicodeEmoji("\ud83d\udcd4")
    object Ledger : UnicodeEmoji("\ud83d\udcd2")
    object Books : UnicodeEmoji("\ud83d\udcda")
    object Book : UnicodeEmoji("\ud83d\udcd6")
    object Link : UnicodeEmoji("\ud83d\udd17")
    object Paperclip : UnicodeEmoji("\ud83d\udcce")
    object Paperclips : UnicodeEmoji("\ud83d\udd87")
    object Scissors : UnicodeEmoji("\u2702")
    object TriangularRuler : UnicodeEmoji("\ud83d\udcd0")
    object StraightRuler : UnicodeEmoji("\ud83d\udccf")
    object Pushpin : UnicodeEmoji("\ud83d\udccc")
    object RoundPushpin : UnicodeEmoji("\ud83d\udccd")
    object TriangularFlagOnPost : UnicodeEmoji("\ud83d\udea9")
    object FlagWhite : UnicodeEmoji("\ud83c\udff3")
    object FlagBlack : UnicodeEmoji("\ud83c\udff4")
    object ClosedLockWithKey : UnicodeEmoji("\ud83d\udd10")
    object Lock : UnicodeEmoji("\ud83d\udd12")
    object Unlock : UnicodeEmoji("\ud83d\udd13")
    object LockWithInkPen : UnicodeEmoji("\ud83d\udd0f")
    object PenBallpoint : UnicodeEmoji("\ud83d\udd8a")
    object PenFountain : UnicodeEmoji("\ud83d\udd8b")
    object BlackNib : UnicodeEmoji("\u2712")
    object Memo : UnicodeEmoji("\ud83d\udcdd")
    object Pencil2 : UnicodeEmoji("\u270f")
    object Crayon : UnicodeEmoji("\ud83d\udd8d")
    object Paintbrush : UnicodeEmoji("\ud83d\udd8c")
    object Mag : UnicodeEmoji("\ud83d\udd0d")
    object MagRight : UnicodeEmoji("\ud83d\udd0e")
    object ShoppingCart : UnicodeEmoji("\ud83d\uded2")

    // Symbols

    object OneHundred : UnicodeEmoji("\ud83d\udcaf")
    object OneTwoThreeFour : UnicodeEmoji("\ud83d\udd22")
    object Heart : UnicodeEmoji("\u2764")
    object YellowHeart : UnicodeEmoji("\ud83d\udc9b")
    object GreenHeart : UnicodeEmoji("\ud83d\udc9a")
    object BlueHeart : UnicodeEmoji("\ud83d\udc99")
    object PurpleHeart : UnicodeEmoji("\ud83d\udc9c")
    object BrokenHeart : UnicodeEmoji("\ud83d\udc94")
    object HeartExclamation : UnicodeEmoji("\u2763")
    object TwoHearts : UnicodeEmoji("\ud83d\udc95")
    object RevolvingHearts : UnicodeEmoji("\ud83d\udc9e")
    object Heartbeat : UnicodeEmoji("\ud83d\udc93")
    object Heartpulse : UnicodeEmoji("\ud83d\udc97")
    object SparklingHeart : UnicodeEmoji("\ud83d\udc96")
    object Cupid : UnicodeEmoji("\ud83d\udc98")
    object GiftHeart : UnicodeEmoji("\ud83d\udc9d")
    object HeartDecoration : UnicodeEmoji("\ud83d\udc9f")
    object Peace : UnicodeEmoji("\u262e")
    object Cross : UnicodeEmoji("\u271d")
    object StarAndCrescent : UnicodeEmoji("\u262a")
    object OmSymbol : UnicodeEmoji("\ud83d\udd49")
    object WheelOfDharma : UnicodeEmoji("\u2638")
    object StarOfDavid : UnicodeEmoji("\u2721")
    object SixPointedStar : UnicodeEmoji("\ud83d\udd2f")
    object Menorah : UnicodeEmoji("\ud83d\udd4e")
    object YinYang : UnicodeEmoji("\u262f")
    object OrthodoxCross : UnicodeEmoji("\u2626")
    object PlaceOfWorship : UnicodeEmoji("\ud83d\uded0")
    object Ophiuchus : UnicodeEmoji("\u26ce")
    object Aries : UnicodeEmoji("\u2648")
    object Taurus : UnicodeEmoji("\u2649")
    object Gemini : UnicodeEmoji("\u264a")
    object Cancer : UnicodeEmoji("\u264b")
    object Leo : UnicodeEmoji("\u264c")
    object Virgo : UnicodeEmoji("\u264d")
    object Libra : UnicodeEmoji("\u264e")
    object Scorpius : UnicodeEmoji("\u264f")
    object Sagittarius : UnicodeEmoji("\u2650")
    object Capricorn : UnicodeEmoji("\u2651")
    object Aquarius : UnicodeEmoji("\u2652")
    object Pisces : UnicodeEmoji("\u2653")
    object ID : UnicodeEmoji("\ud83c\udd94")
    object Atom : UnicodeEmoji("\u269b")
    object U7a7a : UnicodeEmoji("\ud83c\ude33")
    object U5272 : UnicodeEmoji("\ud83c\ude39")
    object Radioactive : UnicodeEmoji("\u2622")
    object Biohazard : UnicodeEmoji("\u2623")
    object MobilePhoneOff : UnicodeEmoji("\ud83d\udcf4")
    object VibrationMode : UnicodeEmoji("\ud83d\udcf3")
    object U6709 : UnicodeEmoji("\ud83c\ude36")
    object U7121 : UnicodeEmoji("\ud83c\ude1a")
    object U7533 : UnicodeEmoji("\ud83c\ude38")
    object U55b6 : UnicodeEmoji("\ud83c\ude3a")
    object U6708 : UnicodeEmoji("\ud83c\ude37")
    object EightPointedBlackStar : UnicodeEmoji("\u2734")
    object VS : UnicodeEmoji("\ud83c\udd9a")
    object Accept : UnicodeEmoji("\ud83c\ude51")
    object WhiteFlower : UnicodeEmoji("\ud83d\udcae")
    object IdeographAdvantage : UnicodeEmoji("\ud83c\ude50")
    object Secret : UnicodeEmoji("\u3299")
    object Congratulations : UnicodeEmoji("\u3297")
    object U5408 : UnicodeEmoji("\ud83c\ude34")
    object U6e80 : UnicodeEmoji("\ud83c\ude35")
    object U7981 : UnicodeEmoji("\ud83c\ude32")
    object A : UnicodeEmoji("\ud83c\udd70")
    object B : UnicodeEmoji("\ud83c\udd71")
    object AB : UnicodeEmoji("\ud83c\udd8e")
    object CL : UnicodeEmoji("\ud83c\udd91")
    object O2 : UnicodeEmoji("\ud83c\udd7e")
    object Sos : UnicodeEmoji("\ud83c\udd98")
    object NoEntry : UnicodeEmoji("\u26d4")
    object NameBadge : UnicodeEmoji("\ud83d\udcdb")
    object NoEntrySign : UnicodeEmoji("\ud83d\udeab")
    /** A red 'X' */
    object X : UnicodeEmoji("\u274c")
    object O : UnicodeEmoji("\u2b55")
    object Anger : UnicodeEmoji("\ud83d\udca2")
    object Hotsprings : UnicodeEmoji("\u2668")
    object NoPedestrians : UnicodeEmoji("\ud83d\udeb7")
    object DoNotLitter : UnicodeEmoji("\ud83d\udeaf")
    object NoBicycles : UnicodeEmoji("\ud83d\udeb3")
    object NonPotableWater : UnicodeEmoji("\ud83d\udeb1")
    object Underage : UnicodeEmoji("\ud83d\udd1e")
    object NoMobilePhones : UnicodeEmoji("\ud83d\udcf5")
    object Exclamation : UnicodeEmoji("\u2757")
    object GreyExclamation : UnicodeEmoji("\u2755")
    object Question : UnicodeEmoji("\u2753")
    object GreyQuestion : UnicodeEmoji("\u2754")
    object Bangbang : UnicodeEmoji("\u203c")
    object Interrobang : UnicodeEmoji("\u2049")
    object LowBrightness : UnicodeEmoji("\ud83d\udd05")
    object HighBrightness : UnicodeEmoji("\ud83d\udd06")
    object Trident : UnicodeEmoji("\ud83d\udd31")
    object FleurDeLis : UnicodeEmoji("\u269c")
    object PartAlternationMark : UnicodeEmoji("\u303d")
    object Warning : UnicodeEmoji("\u26a0")
    object ChildrenCrossing : UnicodeEmoji("\ud83d\udeb8")
    object Beginner : UnicodeEmoji("\ud83d\udd30")
    object Recycle : UnicodeEmoji("\u267b")
    object U6307 : UnicodeEmoji("\ud83c\ude2f")
    object Chart : UnicodeEmoji("\ud83d\udcb9")
    object Sparkle : UnicodeEmoji("\u2747")
    object EightSpokedAsterisk : UnicodeEmoji("\u2733")
    object NegativeSquaredCrossMark : UnicodeEmoji("\u274e")
    object WhiteCheckMark : UnicodeEmoji("\u2705")
    object DiamondShapeWithADotInside : UnicodeEmoji("\ud83d\udca0")
    object Cyclone : UnicodeEmoji("\ud83c\udf00")
    object Loop : UnicodeEmoji("\u27bf")
    object GlobeWithMeridians : UnicodeEmoji("\ud83c\udf10")
    object M : UnicodeEmoji("\u24c2")
    object Atm : UnicodeEmoji("\ud83c\udfe7")
    object SA : UnicodeEmoji("\ud83c\ude02")
    object PassportControl : UnicodeEmoji("\ud83d\udec2")
    object Customs : UnicodeEmoji("\ud83d\udec3")
    object BaggageClaim : UnicodeEmoji("\ud83d\udec4")
    object LeftLuggage : UnicodeEmoji("\ud83d\udec5")
    object Wheelchair : UnicodeEmoji("\u267f")
    object NoSmoking : UnicodeEmoji("\ud83d\udead")
    object WC : UnicodeEmoji("\ud83d\udebe")
    object Parking : UnicodeEmoji("\ud83c\udd7f")
    object PotableWater : UnicodeEmoji("\ud83d\udeb0")
    object Mens : UnicodeEmoji("\ud83d\udeb9")
    object Womens : UnicodeEmoji("\ud83d\udeba")
    object BabySymbol : UnicodeEmoji("\ud83d\udebc")
    object Restroom : UnicodeEmoji("\ud83d\udebb")
    object PutLitterInItsPlace : UnicodeEmoji("\ud83d\udeae")
    object Cinema : UnicodeEmoji("\ud83c\udfa6")
    object SignalStrength : UnicodeEmoji("\ud83d\udcf6")
    object Koko : UnicodeEmoji("\ud83c\ude01")
    object NG : UnicodeEmoji("\ud83c\udd96")
    object OK : UnicodeEmoji("\ud83c\udd97")
    object UP : UnicodeEmoji("\ud83c\udd99")
    object Cool : UnicodeEmoji("\ud83c\udd92")
    object New : UnicodeEmoji("\ud83c\udd95")
    object Free : UnicodeEmoji("\ud83c\udd93")
    object Zero : UnicodeEmoji("\u0030\u20e3")
    object One : UnicodeEmoji("\u0031\u20e3")
    object Two : UnicodeEmoji("\u0032\u20e3")
    object Three : UnicodeEmoji("\u0033\u20e3")
    object Four : UnicodeEmoji("\u0034\u20e3")
    object Five : UnicodeEmoji("\u0035\u20e3")
    object Six : UnicodeEmoji("\u0036\u20e3")
    object Seven : UnicodeEmoji("\u0037\u20e3")
    object Eight : UnicodeEmoji("\u0038\u20e3")
    object Nine : UnicodeEmoji("\u0039\u20e3")
    object Ten : UnicodeEmoji("\ud83d\udd1f")
    object ArrowForward : UnicodeEmoji("\u25b6")
    object PauseButton : UnicodeEmoji("\u23f8")
    object PlayPause : UnicodeEmoji("\u23ef")
    object StopButton : UnicodeEmoji("\u23f9")
    object RecordButton : UnicodeEmoji("\u23fa")
    object TrackNext : UnicodeEmoji("\u23ed")
    object TrackPrevious : UnicodeEmoji("\u23ee")
    object FastForward : UnicodeEmoji("\u23e9")
    object Rewind : UnicodeEmoji("\u23ea")
    object TwistedRightwardsArrows : UnicodeEmoji("\ud83d\udd00")
    object Repeat : UnicodeEmoji("\ud83d\udd01")
    object RepeatOne : UnicodeEmoji("\ud83d\udd02")
    object ArrowBackward : UnicodeEmoji("\u25c0")
    object ArrowUpSmall : UnicodeEmoji("\ud83d\udd3c")
    object ArrowDownSmall : UnicodeEmoji("\ud83d\udd3d")
    object ArrowDoubleUp : UnicodeEmoji("\u23eb")
    object ArrowDoubleDown : UnicodeEmoji("\u23ec")
    object ArrowRight : UnicodeEmoji("\u27a1")
    object ArrowLeft : UnicodeEmoji("\u2b05")
    object ArrowUp : UnicodeEmoji("\u2b06")
    object ArrowDown : UnicodeEmoji("\u2b07")
    object ArrowUpperRight : UnicodeEmoji("\u2197")
    object ArrowLowerRight : UnicodeEmoji("\u2198")
    object ArrowLowerLeft : UnicodeEmoji("\u2199")
    object ArrowUpperLeft : UnicodeEmoji("\u2196")
    object ArrowUpDown : UnicodeEmoji("\u2195")
    object LeftRightArrow : UnicodeEmoji("\u2194")
    object ArrowsCounterclockwise : UnicodeEmoji("\ud83d\udd04")
    object ArrowRightHook : UnicodeEmoji("\u21aa")
    object LeftwardsArrowWithHook : UnicodeEmoji("\u21a9")
    object ArrowHeadingUp : UnicodeEmoji("\u2934")
    object ArrowHeadingDown : UnicodeEmoji("\u2935")
    object Hash : UnicodeEmoji("\u0023\u20e3")
    object Asterisk : UnicodeEmoji("\u002a\u20e3")
    object InformationSource : UnicodeEmoji("\u2139")
    object Abc : UnicodeEmoji("\ud83d\udd24")
    object Abcd : UnicodeEmoji("\ud83d\udd21")
    object CapitalAbcd : UnicodeEmoji("\ud83d\udd20")
    object Symbols : UnicodeEmoji("\ud83d\udd23")
    object MusicalNote : UnicodeEmoji("\ud83c\udfb5")
    object Notes : UnicodeEmoji("\ud83c\udfb6")
    object WavyDash : UnicodeEmoji("\u3030")
    object CurlyLoop : UnicodeEmoji("\u27b0")
    object HeavyCheckMark : UnicodeEmoji("\u2714")
    object ArrowsClockwise : UnicodeEmoji("\ud83d\udd03")
    object HeavyPlusSign : UnicodeEmoji("\u2795")
    object HeavyMinusSign : UnicodeEmoji("\u2796")
    object HeavyDivisionSign : UnicodeEmoji("\u2797")
    object HeavyMultiplicationX : UnicodeEmoji("\u2716")
    object HeavyDollarSign : UnicodeEmoji("\ud83d\udcb2")
    object CurrencyExchange : UnicodeEmoji("\ud83d\udcb1")
    object Copyright : UnicodeEmoji("\u00a9")
    object Registered : UnicodeEmoji("\u00ae")
    object TM : UnicodeEmoji("\u2122")
    object End : UnicodeEmoji("\ud83d\udd1a")
    object Back : UnicodeEmoji("\ud83d\udd19")
    object ON : UnicodeEmoji("\ud83d\udd1b")
    object Top : UnicodeEmoji("\ud83d\udd1d")
    object Soon : UnicodeEmoji("\ud83d\udd1c")
    object BallotBoxWithCheck : UnicodeEmoji("\u2611")
    object RadioButton : UnicodeEmoji("\ud83d\udd18")
    object WhiteCircle : UnicodeEmoji("\u26aa")
    object BlackCircle : UnicodeEmoji("\u26ab")
    object RedCircle : UnicodeEmoji("\ud83d\udd34")
    object LargeBlueCircle : UnicodeEmoji("\ud83d\udd35")
    object SmallOrangeDiamond : UnicodeEmoji("\ud83d\udd38")
    object SmallBlueDiamond : UnicodeEmoji("\ud83d\udd39")
    object LargeOrangeDiamond : UnicodeEmoji("\ud83d\udd36")
    object LargeBlueDiamond : UnicodeEmoji("\ud83d\udd37")
    object SmallRedTriangle : UnicodeEmoji("\ud83d\udd3a")
    object BlackSmallSquare : UnicodeEmoji("\u25aa")
    object WhiteSmallSquare : UnicodeEmoji("\u25ab")
    object BlackLargeSquare : UnicodeEmoji("\u2b1b")
    object WhiteLargeSquare : UnicodeEmoji("\u2b1c")
    object SmallRedTriangleDown : UnicodeEmoji("\ud83d\udd3b")
    object BlackMediumSquare : UnicodeEmoji("\u25fc")
    object WhiteMediumSquare : UnicodeEmoji("\u25fb")
    object BlackMediumSmallSquare : UnicodeEmoji("\u25fe")
    object WhiteMediumSmallSquare : UnicodeEmoji("\u25fd")
    object BlackSquareButton : UnicodeEmoji("\ud83d\udd32")
    object WhiteSquareButton : UnicodeEmoji("\ud83d\udd33")
    object Speaker : UnicodeEmoji("\ud83d\udd08")
    object Sound : UnicodeEmoji("\ud83d\udd09")
    object LoudSound : UnicodeEmoji("\ud83d\udd0a")
    object Mute : UnicodeEmoji("\ud83d\udd07")
    object Mega : UnicodeEmoji("\ud83d\udce3")
    object Loudspeaker : UnicodeEmoji("\ud83d\udce2")
    object Bell : UnicodeEmoji("\ud83d\udd14")
    object NoBell : UnicodeEmoji("\ud83d\udd15")
    object BlackJoker : UnicodeEmoji("\ud83c\udccf")
    object Mahjong : UnicodeEmoji("\ud83c\udc04")
    object Spades : UnicodeEmoji("\u2660")
    object Clubs : UnicodeEmoji("\u2663")
    object Hearts : UnicodeEmoji("\u2665")
    object Diamonds : UnicodeEmoji("\u2666")
    object FlowerPlayingCards : UnicodeEmoji("\ud83c\udfb4")
    object ThoughtBalloon : UnicodeEmoji("\ud83d\udcad")
    object AngerRight : UnicodeEmoji("\ud83d\uddef")
    object SpeechBalloon : UnicodeEmoji("\ud83d\udcac")
    object Clock1 : UnicodeEmoji("\ud83d\udd50")
    object Clock2 : UnicodeEmoji("\ud83d\udd51")
    object Clock3 : UnicodeEmoji("\ud83d\udd52")
    object Clock4 : UnicodeEmoji("\ud83d\udd53")
    object Clock5 : UnicodeEmoji("\ud83d\udd54")
    object Clock6 : UnicodeEmoji("\ud83d\udd55")
    object Clock7 : UnicodeEmoji("\ud83d\udd56")
    object Clock8 : UnicodeEmoji("\ud83d\udd57")
    object Clock9 : UnicodeEmoji("\ud83d\udd58")
    object Clock10 : UnicodeEmoji("\ud83d\udd59")
    object Clock11 : UnicodeEmoji("\ud83d\udd5a")
    object Clock12 : UnicodeEmoji("\ud83d\udd5b")
    object Clock130 : UnicodeEmoji("\ud83d\udd5c")
    object Clock230 : UnicodeEmoji("\ud83d\udd5d")
    object Clock330 : UnicodeEmoji("\ud83d\udd5e")
    object Clock430 : UnicodeEmoji("\ud83d\udd5f")
    object Clock530 : UnicodeEmoji("\ud83d\udd60")
    object Clock630 : UnicodeEmoji("\ud83d\udd61")
    object Clock730 : UnicodeEmoji("\ud83d\udd62")
    object Clock830 : UnicodeEmoji("\ud83d\udd63")
    object Clock930 : UnicodeEmoji("\ud83d\udd64")
    object Clock1030 : UnicodeEmoji("\ud83d\udd65")
    object Clock1130 : UnicodeEmoji("\ud83d\udd66")
    object Clock1230 : UnicodeEmoji("\ud83d\udd67")
    object EyeInSpeechBubble : UnicodeEmoji("\ud83d\udc41\u200d\ud83d\udde8")
    object SpeechLeft : UnicodeEmoji("\ud83d\udde8")
    object Eject : UnicodeEmoji("\u23cf")
    object BlackHeart : UnicodeEmoji("\ud83d\udda4")
    object StopSign : UnicodeEmoji("\ud83d\uded1")
    object RegionalIndicatorZ : UnicodeEmoji("\ud83c\uddff")
    object RegionalIndicatorY : UnicodeEmoji("\ud83c\uddfe")
    object RegionalIndicatorX : UnicodeEmoji("\ud83c\uddfd")
    object RegionalIndicatorW : UnicodeEmoji("\ud83c\uddfc")
    object RegionalIndicatorV : UnicodeEmoji("\ud83c\uddfb")
    object RegionalIndicatorU : UnicodeEmoji("\ud83c\uddfa")
    object RegionalIndicatorT : UnicodeEmoji("\ud83c\uddf9")
    object RegionalIndicatorS : UnicodeEmoji("\ud83c\uddf8")
    object RegionalIndicatorR : UnicodeEmoji("\ud83c\uddf7")
    object RegionalIndicatorQ : UnicodeEmoji("\ud83c\uddf6")
    object RegionalIndicatorP : UnicodeEmoji("\ud83c\uddf5")
    object RegionalIndicatorO : UnicodeEmoji("\ud83c\uddf4")
    object RegionalIndicatorN : UnicodeEmoji("\ud83c\uddf3")
    object RegionalIndicatorM : UnicodeEmoji("\ud83c\uddf2")
    object RegionalIndicatorL : UnicodeEmoji("\ud83c\uddf1")
    object RegionalIndicatorK : UnicodeEmoji("\ud83c\uddf0")
    object RegionalIndicatorJ : UnicodeEmoji("\ud83c\uddef")
    object RegionalIndicatorI : UnicodeEmoji("\ud83c\uddee")
    object RegionalIndicatorH : UnicodeEmoji("\ud83c\udded")
    object RegionalIndicatorG : UnicodeEmoji("\ud83c\uddec")
    object RegionalIndicatorF : UnicodeEmoji("\ud83c\uddeb")
    object RegionalIndicatorE : UnicodeEmoji("\ud83c\uddea")
    object RegionalIndicatorD : UnicodeEmoji("\ud83c\udde9")
    object RegionalIndicatorC : UnicodeEmoji("\ud83c\udde8")
    object RegionalIndicatorB : UnicodeEmoji("\ud83c\udde7")
    object RegionalIndicatorA : UnicodeEmoji("\ud83c\udde6")

    // Flags

    object FlagAC : UnicodeEmoji("\ud83c\udde6\ud83c\udde8")
    object FlagAD : UnicodeEmoji("\ud83c\udde6\ud83c\udde9")
    object FlagAE : UnicodeEmoji("\ud83c\udde6\ud83c\uddea")
    object FlagAF : UnicodeEmoji("\ud83c\udde6\ud83c\uddeb")
    object FlagAG : UnicodeEmoji("\ud83c\udde6\ud83c\uddec")
    object FlagAI : UnicodeEmoji("\ud83c\udde6\ud83c\uddee")
    object FlagAL : UnicodeEmoji("\ud83c\udde6\ud83c\uddf1")
    object FlagAM : UnicodeEmoji("\ud83c\udde6\ud83c\uddf2")
    object FlagAO : UnicodeEmoji("\ud83c\udde6\ud83c\uddf4")
    object FlagAQ : UnicodeEmoji("\ud83c\udde6\ud83c\uddf6")
    object FlagAR : UnicodeEmoji("\ud83c\udde6\ud83c\uddf7")
    object FlagAS : UnicodeEmoji("\ud83c\udde6\ud83c\uddf8")
    object FlagAT : UnicodeEmoji("\ud83c\udde6\ud83c\uddf9")
    object FlagAU : UnicodeEmoji("\ud83c\udde6\ud83c\uddfa")
    object FlagAW : UnicodeEmoji("\ud83c\udde6\ud83c\uddfc")
    object FlagAX : UnicodeEmoji("\ud83c\udde6\ud83c\uddfd")
    object FlagAZ : UnicodeEmoji("\ud83c\udde6\ud83c\uddff")
    object FlagBA : UnicodeEmoji("\ud83c\udde7\ud83c\udde6")
    object FlagBB : UnicodeEmoji("\ud83c\udde7\ud83c\udde7")
    object FlagBD : UnicodeEmoji("\ud83c\udde7\ud83c\udde9")
    object FlagBE : UnicodeEmoji("\ud83c\udde7\ud83c\uddea")
    object FlagBF : UnicodeEmoji("\ud83c\udde7\ud83c\uddeb")
    object FlagBG : UnicodeEmoji("\ud83c\udde7\ud83c\uddec")
    object FlagBH : UnicodeEmoji("\ud83c\udde7\ud83c\udded")
    object FlagBI : UnicodeEmoji("\ud83c\udde7\ud83c\uddee")
    object FlagBJ : UnicodeEmoji("\ud83c\udde7\ud83c\uddef")
    object FlagBL : UnicodeEmoji("\ud83c\udde7\ud83c\uddf1")
    object FlagBM : UnicodeEmoji("\ud83c\udde7\ud83c\uddf2")
    object FlagBN : UnicodeEmoji("\ud83c\udde7\ud83c\uddf3")
    object FlagBO : UnicodeEmoji("\ud83c\udde7\ud83c\uddf4")
    object FlagBQ : UnicodeEmoji("\ud83c\udde7\ud83c\uddf6")
    object FlagBR : UnicodeEmoji("\ud83c\udde7\ud83c\uddf7")
    object FlagBS : UnicodeEmoji("\ud83c\udde7\ud83c\uddf8")
    object FlagBT : UnicodeEmoji("\ud83c\udde7\ud83c\uddf9")
    object FlagBV : UnicodeEmoji("\ud83c\udde7\ud83c\uddfb")
    object FlagBW : UnicodeEmoji("\ud83c\udde7\ud83c\uddfc")
    object FlagBY : UnicodeEmoji("\ud83c\udde7\ud83c\uddfe")
    object FlagBZ : UnicodeEmoji("\ud83c\udde7\ud83c\uddff")
    object FlagCA : UnicodeEmoji("\ud83c\udde8\ud83c\udde6")
    object FlagCC : UnicodeEmoji("\ud83c\udde8\ud83c\udde8")
    object FlagCD : UnicodeEmoji("\ud83c\udde8\ud83c\udde9")
    object FlagCF : UnicodeEmoji("\ud83c\udde8\ud83c\uddeb")
    object FlagCG : UnicodeEmoji("\ud83c\udde8\ud83c\uddec")
    object FlagCH : UnicodeEmoji("\ud83c\udde8\ud83c\udded")
    object FlagCI : UnicodeEmoji("\ud83c\udde8\ud83c\uddee")
    object FlagCK : UnicodeEmoji("\ud83c\udde8\ud83c\uddf0")
    object FlagCL : UnicodeEmoji("\ud83c\udde8\ud83c\uddf1")
    object FlagCM : UnicodeEmoji("\ud83c\udde8\ud83c\uddf2")
    object FlagCN : UnicodeEmoji("\ud83c\udde8\ud83c\uddf3")
    object FlagCO : UnicodeEmoji("\ud83c\udde8\ud83c\uddf4")
    object FlagCP : UnicodeEmoji("\ud83c\udde8\ud83c\uddf5")
    object FlagCR : UnicodeEmoji("\ud83c\udde8\ud83c\uddf7")
    object FlagCU : UnicodeEmoji("\ud83c\udde8\ud83c\uddfa")
    object FlagCV : UnicodeEmoji("\ud83c\udde8\ud83c\uddfb")
    object FlagCW : UnicodeEmoji("\ud83c\udde8\ud83c\uddfc")
    object FlagCX : UnicodeEmoji("\ud83c\udde8\ud83c\uddfd")
    object FlagCY : UnicodeEmoji("\ud83c\udde8\ud83c\uddfe")
    object FlagCZ : UnicodeEmoji("\ud83c\udde8\ud83c\uddff")
    object FlagDE : UnicodeEmoji("\ud83c\udde9\ud83c\uddea")
    object FlagDG : UnicodeEmoji("\ud83c\udde9\ud83c\uddec")
    object FlagDJ : UnicodeEmoji("\ud83c\udde9\ud83c\uddef")
    object FlagDK : UnicodeEmoji("\ud83c\udde9\ud83c\uddf0")
    object FlagDM : UnicodeEmoji("\ud83c\udde9\ud83c\uddf2")
    object FlagDO : UnicodeEmoji("\ud83c\udde9\ud83c\uddf4")
    object FlagDZ : UnicodeEmoji("\ud83c\udde9\ud83c\uddff")
    object FlagEA : UnicodeEmoji("\ud83c\uddea\ud83c\udde6")
    object FlagEC : UnicodeEmoji("\ud83c\uddea\ud83c\udde8")
    object FlagEE : UnicodeEmoji("\ud83c\uddea\ud83c\uddea")
    object FlagEG : UnicodeEmoji("\ud83c\uddea\ud83c\uddec")
    object FlagEH : UnicodeEmoji("\ud83c\uddea\ud83c\udded")
    object FlagER : UnicodeEmoji("\ud83c\uddea\ud83c\uddf7")
    object FlagES : UnicodeEmoji("\ud83c\uddea\ud83c\uddf8")
    object FlagET : UnicodeEmoji("\ud83c\uddea\ud83c\uddf9")
    object FlagEU : UnicodeEmoji("\ud83c\uddea\ud83c\uddfa")
    object FlagFI : UnicodeEmoji("\ud83c\uddeb\ud83c\uddee")
    object FlagFJ : UnicodeEmoji("\ud83c\uddeb\ud83c\uddef")
    object FlagFK : UnicodeEmoji("\ud83c\uddeb\ud83c\uddf0")
    object FlagFM : UnicodeEmoji("\ud83c\uddeb\ud83c\uddf2")
    object FlagFO : UnicodeEmoji("\ud83c\uddeb\ud83c\uddf4")
    object FlagFR : UnicodeEmoji("\ud83c\uddeb\ud83c\uddf7")
    object FlagGA : UnicodeEmoji("\ud83c\uddec\ud83c\udde6")
    object FlagGB : UnicodeEmoji("\ud83c\uddec\ud83c\udde7")
    object FlagGD : UnicodeEmoji("\ud83c\uddec\ud83c\udde9")
    object FlagGE : UnicodeEmoji("\ud83c\uddec\ud83c\uddea")
    object FlagGF : UnicodeEmoji("\ud83c\uddec\ud83c\uddeb")
    object FlagGG : UnicodeEmoji("\ud83c\uddec\ud83c\uddec")
    object FlagGH : UnicodeEmoji("\ud83c\uddec\ud83c\udded")
    object FlagGI : UnicodeEmoji("\ud83c\uddec\ud83c\uddee")
    object FlagGL : UnicodeEmoji("\ud83c\uddec\ud83c\uddf1")
    object FlagGM : UnicodeEmoji("\ud83c\uddec\ud83c\uddf2")
    object FlagGN : UnicodeEmoji("\ud83c\uddec\ud83c\uddf3")
    object FlagGP : UnicodeEmoji("\ud83c\uddec\ud83c\uddf5")
    object FlagGQ : UnicodeEmoji("\ud83c\uddec\ud83c\uddf6")
    object FlagGR : UnicodeEmoji("\ud83c\uddec\ud83c\uddf7")
    object FlagGS : UnicodeEmoji("\ud83c\uddec\ud83c\uddf8")
    object FlagGT : UnicodeEmoji("\ud83c\uddec\ud83c\uddf9")
    object FlagGU : UnicodeEmoji("\ud83c\uddec\ud83c\uddfa")
    object FlagGW : UnicodeEmoji("\ud83c\uddec\ud83c\uddfc")
    object FlagGY : UnicodeEmoji("\ud83c\uddec\ud83c\uddfe")
    object FlagHK : UnicodeEmoji("\ud83c\udded\ud83c\uddf0")
    object FlagHM : UnicodeEmoji("\ud83c\udded\ud83c\uddf2")
    object FlagHN : UnicodeEmoji("\ud83c\udded\ud83c\uddf3")
    object FlagHR : UnicodeEmoji("\ud83c\udded\ud83c\uddf7")
    object FlagHT : UnicodeEmoji("\ud83c\udded\ud83c\uddf9")
    object FlagHU : UnicodeEmoji("\ud83c\udded\ud83c\uddfa")
    object FlagIC : UnicodeEmoji("\ud83c\uddee\ud83c\udde8")
    object FlagID : UnicodeEmoji("\ud83c\uddee\ud83c\udde9")
    object FlagIE : UnicodeEmoji("\ud83c\uddee\ud83c\uddea")
    object FlagIL : UnicodeEmoji("\ud83c\uddee\ud83c\uddf1")
    object FlagIM : UnicodeEmoji("\ud83c\uddee\ud83c\uddf2")
    object FlagIN : UnicodeEmoji("\ud83c\uddee\ud83c\uddf3")
    object FlagIO : UnicodeEmoji("\ud83c\uddee\ud83c\uddf4")
    object FlagIQ : UnicodeEmoji("\ud83c\uddee\ud83c\uddf6")
    object FlagIR : UnicodeEmoji("\ud83c\uddee\ud83c\uddf7")
    object FlagIS : UnicodeEmoji("\ud83c\uddee\ud83c\uddf8")
    object FlagIT : UnicodeEmoji("\ud83c\uddee\ud83c\uddf9")
    object FlagJE : UnicodeEmoji("\ud83c\uddef\ud83c\uddea")
    object FlagJM : UnicodeEmoji("\ud83c\uddef\ud83c\uddf2")
    object FlagJO : UnicodeEmoji("\ud83c\uddef\ud83c\uddf4")
    object FlagJP : UnicodeEmoji("\ud83c\uddef\ud83c\uddf5")
    object FlagKE : UnicodeEmoji("\ud83c\uddf0\ud83c\uddea")
    object FlagKG : UnicodeEmoji("\ud83c\uddf0\ud83c\uddec")
    object FlagKH : UnicodeEmoji("\ud83c\uddf0\ud83c\udded")
    object FlagKI : UnicodeEmoji("\ud83c\uddf0\ud83c\uddee")
    object FlagKM : UnicodeEmoji("\ud83c\uddf0\ud83c\uddf2")
    object FlagKN : UnicodeEmoji("\ud83c\uddf0\ud83c\uddf3")
    object FlagKP : UnicodeEmoji("\ud83c\uddf0\ud83c\uddf5")
    object FlagKR : UnicodeEmoji("\ud83c\uddf0\ud83c\uddf7")
    object FlagKW : UnicodeEmoji("\ud83c\uddf0\ud83c\uddfc")
    object FlagKY : UnicodeEmoji("\ud83c\uddf0\ud83c\uddfe")
    object FlagKZ : UnicodeEmoji("\ud83c\uddf0\ud83c\uddff")
    object FlagLA : UnicodeEmoji("\ud83c\uddf1\ud83c\udde6")
    object FlagLB : UnicodeEmoji("\ud83c\uddf1\ud83c\udde7")
    object FlagLC : UnicodeEmoji("\ud83c\uddf1\ud83c\udde8")
    object FlagLI : UnicodeEmoji("\ud83c\uddf1\ud83c\uddee")
    object FlagLK : UnicodeEmoji("\ud83c\uddf1\ud83c\uddf0")
    object FlagLR : UnicodeEmoji("\ud83c\uddf1\ud83c\uddf7")
    object FlagLS : UnicodeEmoji("\ud83c\uddf1\ud83c\uddf8")
    object FlagLT : UnicodeEmoji("\ud83c\uddf1\ud83c\uddf9")
    object FlagLU : UnicodeEmoji("\ud83c\uddf1\ud83c\uddfa")
    object FlagLV : UnicodeEmoji("\ud83c\uddf1\ud83c\uddfb")
    object FlagLY : UnicodeEmoji("\ud83c\uddf1\ud83c\uddfe")
    object FlagMA : UnicodeEmoji("\ud83c\uddf2\ud83c\udde6")
    object FlagMC : UnicodeEmoji("\ud83c\uddf2\ud83c\udde8")
    object FlagMD : UnicodeEmoji("\ud83c\uddf2\ud83c\udde9")
    object FlagME : UnicodeEmoji("\ud83c\uddf2\ud83c\uddea")
    object FlagMF : UnicodeEmoji("\ud83c\uddf2\ud83c\uddeb")
    object FlagMG : UnicodeEmoji("\ud83c\uddf2\ud83c\uddec")
    object FlagMH : UnicodeEmoji("\ud83c\uddf2\ud83c\udded")
    object FlagMK : UnicodeEmoji("\ud83c\uddf2\ud83c\uddf0")
    object FlagML : UnicodeEmoji("\ud83c\uddf2\ud83c\uddf1")
    object FlagMM : UnicodeEmoji("\ud83c\uddf2\ud83c\uddf2")
    object FlagMN : UnicodeEmoji("\ud83c\uddf2\ud83c\uddf3")
    object FlagMO : UnicodeEmoji("\ud83c\uddf2\ud83c\uddf4")
    object FlagMP : UnicodeEmoji("\ud83c\uddf2\ud83c\uddf5")
    object FlagMQ : UnicodeEmoji("\ud83c\uddf2\ud83c\uddf6")
    object FlagMR : UnicodeEmoji("\ud83c\uddf2\ud83c\uddf7")
    object FlagMS : UnicodeEmoji("\ud83c\uddf2\ud83c\uddf8")
    object FlagMT : UnicodeEmoji("\ud83c\uddf2\ud83c\uddf9")
    object FlagMU : UnicodeEmoji("\ud83c\uddf2\ud83c\uddfa")
    object FlagMV : UnicodeEmoji("\ud83c\uddf2\ud83c\uddfb")
    object FlagMW : UnicodeEmoji("\ud83c\uddf2\ud83c\uddfc")
    object FlagMX : UnicodeEmoji("\ud83c\uddf2\ud83c\uddfd")
    object FlagMY : UnicodeEmoji("\ud83c\uddf2\ud83c\uddfe")
    object FlagMZ : UnicodeEmoji("\ud83c\uddf2\ud83c\uddff")
    object FlagNA : UnicodeEmoji("\ud83c\uddf3\ud83c\udde6")
    object FlagNC : UnicodeEmoji("\ud83c\uddf3\ud83c\udde8")
    object FlagNE : UnicodeEmoji("\ud83c\uddf3\ud83c\uddea")
    object FlagNF : UnicodeEmoji("\ud83c\uddf3\ud83c\uddeb")
    object FlagNG : UnicodeEmoji("\ud83c\uddf3\ud83c\uddec")
    object FlagNI : UnicodeEmoji("\ud83c\uddf3\ud83c\uddee")
    object FlagNL : UnicodeEmoji("\ud83c\uddf3\ud83c\uddf1")
    object FlagNO : UnicodeEmoji("\ud83c\uddf3\ud83c\uddf4")
    object FlagNP : UnicodeEmoji("\ud83c\uddf3\ud83c\uddf5")
    object FlagNR : UnicodeEmoji("\ud83c\uddf3\ud83c\uddf7")
    object FlagNU : UnicodeEmoji("\ud83c\uddf3\ud83c\uddfa")
    object FlagNZ : UnicodeEmoji("\ud83c\uddf3\ud83c\uddff")
    object FlagOM : UnicodeEmoji("\ud83c\uddf4\ud83c\uddf2")
    object FlagPA : UnicodeEmoji("\ud83c\uddf5\ud83c\udde6")
    object FlagPE : UnicodeEmoji("\ud83c\uddf5\ud83c\uddea")
    object FlagPF : UnicodeEmoji("\ud83c\uddf5\ud83c\uddeb")
    object FlagPG : UnicodeEmoji("\ud83c\uddf5\ud83c\uddec")
    object FlagPH : UnicodeEmoji("\ud83c\uddf5\ud83c\udded")
    object FlagPK : UnicodeEmoji("\ud83c\uddf5\ud83c\uddf0")
    object FlagPL : UnicodeEmoji("\ud83c\uddf5\ud83c\uddf1")
    object FlagPM : UnicodeEmoji("\ud83c\uddf5\ud83c\uddf2")
    object FlagPN : UnicodeEmoji("\ud83c\uddf5\ud83c\uddf3")
    object FlagPR : UnicodeEmoji("\ud83c\uddf5\ud83c\uddf7")
    object FlagPS : UnicodeEmoji("\ud83c\uddf5\ud83c\uddf8")
    object FlagPT : UnicodeEmoji("\ud83c\uddf5\ud83c\uddf9")
    object FlagPW : UnicodeEmoji("\ud83c\uddf5\ud83c\uddfc")
    object FlagPY : UnicodeEmoji("\ud83c\uddf5\ud83c\uddfe")
    object FlagQA : UnicodeEmoji("\ud83c\uddf6\ud83c\udde6")
    object FlagRE : UnicodeEmoji("\ud83c\uddf7\ud83c\uddea")
    object FlagRO : UnicodeEmoji("\ud83c\uddf7\ud83c\uddf4")
    object FlagRS : UnicodeEmoji("\ud83c\uddf7\ud83c\uddf8")
    object FlagRU : UnicodeEmoji("\ud83c\uddf7\ud83c\uddfa")
    object FlagRW : UnicodeEmoji("\ud83c\uddf7\ud83c\uddfc")
    object FlagSA : UnicodeEmoji("\ud83c\uddf8\ud83c\udde6")
    object FlagSB : UnicodeEmoji("\ud83c\uddf8\ud83c\udde7")
    object FlagSC : UnicodeEmoji("\ud83c\uddf8\ud83c\udde8")
    object FlagSD : UnicodeEmoji("\ud83c\uddf8\ud83c\udde9")
    object FlagSE : UnicodeEmoji("\ud83c\uddf8\ud83c\uddea")
    object FlagSG : UnicodeEmoji("\ud83c\uddf8\ud83c\uddec")
    object FlagSH : UnicodeEmoji("\ud83c\uddf8\ud83c\udded")
    object FlagSI : UnicodeEmoji("\ud83c\uddf8\ud83c\uddee")
    object FlagSJ : UnicodeEmoji("\ud83c\uddf8\ud83c\uddef")
    object FlagSK : UnicodeEmoji("\ud83c\uddf8\ud83c\uddf0")
    object FlagSL : UnicodeEmoji("\ud83c\uddf8\ud83c\uddf1")
    object FlagSM : UnicodeEmoji("\ud83c\uddf8\ud83c\uddf2")
    object FlagSN : UnicodeEmoji("\ud83c\uddf8\ud83c\uddf3")
    object FlagSO : UnicodeEmoji("\ud83c\uddf8\ud83c\uddf4")
    object FlagSR : UnicodeEmoji("\ud83c\uddf8\ud83c\uddf7")
    object FlagSS : UnicodeEmoji("\ud83c\uddf8\ud83c\uddf8")
    object FlagST : UnicodeEmoji("\ud83c\uddf8\ud83c\uddf9")
    object FlagSV : UnicodeEmoji("\ud83c\uddf8\ud83c\uddfb")
    object FlagSX : UnicodeEmoji("\ud83c\uddf8\ud83c\uddfd")
    object FlagSY : UnicodeEmoji("\ud83c\uddf8\ud83c\uddfe")
    object FlagSZ : UnicodeEmoji("\ud83c\uddf8\ud83c\uddff")
    object FlagTA : UnicodeEmoji("\ud83c\uddf9\ud83c\udde6")
    object FlagTC : UnicodeEmoji("\ud83c\uddf9\ud83c\udde8")
    object FlagTD : UnicodeEmoji("\ud83c\uddf9\ud83c\udde9")
    object FlagTF : UnicodeEmoji("\ud83c\uddf9\ud83c\uddeb")
    object FlagTG : UnicodeEmoji("\ud83c\uddf9\ud83c\uddec")
    object FlagTH : UnicodeEmoji("\ud83c\uddf9\ud83c\udded")
    object FlagTJ : UnicodeEmoji("\ud83c\uddf9\ud83c\uddef")
    object FlagTK : UnicodeEmoji("\ud83c\uddf9\ud83c\uddf0")
    object FlagTL : UnicodeEmoji("\ud83c\uddf9\ud83c\uddf1")
    object FlagTM : UnicodeEmoji("\ud83c\uddf9\ud83c\uddf2")
    object FlagTN : UnicodeEmoji("\ud83c\uddf9\ud83c\uddf3")
    object FlagTO : UnicodeEmoji("\ud83c\uddf9\ud83c\uddf4")
    object FlagTR : UnicodeEmoji("\ud83c\uddf9\ud83c\uddf7")
    object FlagTT : UnicodeEmoji("\ud83c\uddf9\ud83c\uddf9")
    object FlagTV : UnicodeEmoji("\ud83c\uddf9\ud83c\uddfb")
    object FlagTW : UnicodeEmoji("\ud83c\uddf9\ud83c\uddfc")
    object FlagTZ : UnicodeEmoji("\ud83c\uddf9\ud83c\uddff")
    object FlagUA : UnicodeEmoji("\ud83c\uddfa\ud83c\udde6")
    object FlagUG : UnicodeEmoji("\ud83c\uddfa\ud83c\uddec")
    object FlagUM : UnicodeEmoji("\ud83c\uddfa\ud83c\uddf2")
    object FlagUS : UnicodeEmoji("\ud83c\uddfa\ud83c\uddf8")
    object FlagUY : UnicodeEmoji("\ud83c\uddfa\ud83c\uddfe")
    object FlagUZ : UnicodeEmoji("\ud83c\uddfa\ud83c\uddff")
    object FlagVA : UnicodeEmoji("\ud83c\uddfb\ud83c\udde6")
    object FlagVC : UnicodeEmoji("\ud83c\uddfb\ud83c\udde8")
    object FlagVE : UnicodeEmoji("\ud83c\uddfb\ud83c\uddea")
    object FlagVG : UnicodeEmoji("\ud83c\uddfb\ud83c\uddec")
    object FlagVI : UnicodeEmoji("\ud83c\uddfb\ud83c\uddee")
    object FlagVN : UnicodeEmoji("\ud83c\uddfb\ud83c\uddf3")
    object FlagVU : UnicodeEmoji("\ud83c\uddfb\ud83c\uddfa")
    object FlagWF : UnicodeEmoji("\ud83c\uddfc\ud83c\uddeb")
    object FlagWS : UnicodeEmoji("\ud83c\uddfc\ud83c\uddf8")
    object FlagXK : UnicodeEmoji("\ud83c\uddfd\ud83c\uddf0")
    object FlagYE : UnicodeEmoji("\ud83c\uddfe\ud83c\uddea")
    object FlagYT : UnicodeEmoji("\ud83c\uddfe\ud83c\uddf9")
    object FlagZA : UnicodeEmoji("\ud83c\uddff\ud83c\udde6")
    object FlagZM : UnicodeEmoji("\ud83c\uddff\ud83c\uddf2")
    object FlagZW : UnicodeEmoji("\ud83c\uddff\ud83c\uddfc")
    object GayPrideFlag : UnicodeEmoji("\ud83c\udff3\ufe0f\u200d\ud83c\udf08")

    /** Unknown unicode emoji provided by the user or discord. */
    class Unknown internal constructor(unicode: String) : UnicodeEmoji(unicode)

    /** Get this [UnicodeEmoji] as [String] (aka [combinedUnicode]). */
    override fun toString() = combinedUnicode

    /** Check if [other] is the same as this [UnicodeEmoji]. */
    override fun equals(other: Any?) = other.toString() == toString()

    companion object {
        /** A list of 0-10 emojis. */
        val Numbers = listOf(Zero, One, Two, Three, Four, Five, Six, Seven, Eight, Nine, Ten)

        operator fun invoke(unicode: String): UnicodeEmoji = Unknown(unicode)
    }
}

/**
 * An enum containing a list of supported skin tones. Can be used in a [UnicodeEmoji]'s constructor if it supports
 * skin tones.
 */
enum class SkinTone(val unicode: String) {
    LIGHT("\ud83c\udffb"),
    MEDIUM_LIGHT("\ud83c\udffc"),
    MEDIUM("\ud83c\udffd"),
    MEDIUM_DARK("\ud83c\udffe"),
    DARK("\ud83c\udfff")
}

/** Converts a [PartialEmojiPacket] to an [Emoji]. */
internal fun PartialEmojiPacket.toEmoji(context: BotClient): Emoji =
    id?.let { ForeignGuildEmoji(context, id, name) } ?: UnicodeEmoji(name)